Ext.define('MES.mixin.Constant', function() {
	//Transaction Code
	SF_TRAN_CODE_CREATE = "CREATE";
	SF_TRAN_CODE_START = "START";
	SF_TRAN_CODE_END = "END";
	SF_TRAN_CODE_MOVE = "MOVE";
	SF_TRAN_CODE_SKIP = "SKIP";
	SF_TRAN_CODE_REWORK = "REWORK";
	SF_TRAN_CODE_REPAIR = "REPAIR";
	SF_TRAN_CODE_REPAIR_END = "REPAIR_END";
	SF_TRAN_CODE_LOCAL_REPAIR = "LOCAL_REPAIR";
	SF_TRAN_CODE_LOSS = "LOSS";
	SF_TRAN_CODE_BONUS = "BONUS";
	SF_TRAN_CODE_SPLIT = "SPLIT";
	SF_TRAN_CODE_MERGE = "MERGE";
	SF_TRAN_CODE_COMBINE = "COMBINE";
	SF_TRAN_CODE_HOLD = "HOLD";
	SF_TRAN_CODE_RELEASE = "RELEASE";
	SF_TRAN_CODE_SHIP = "SHIP";
	SF_TRAN_CODE_RECEIVE = "RECEIVE";
	SF_TRAN_CODE_ADAPT = "ADAPT";
	SF_TRAN_CODE_ATTRIBUTE = "ATTRIBUTE";
	SF_TRAN_CODE_LOTEDC = "LOTEDC";
	SF_TRAN_CODE_RESEDC = "RESEDC";
	SF_TRAN_CODE_SORT = "SORT";

	SF_TRAN_CODE_IN_INV = "IN INV";
	SF_TRAN_CODE_OUT_INV = "OUT INV";
	SF_TRAN_CODE_TRANSFER_INV = "TRANS INV";
	SF_TRAN_CODE_CONV_TO_LOT = "CONV TO LOT";
	SF_TRAN_CODE_CONV_TO_INV = "CONV TO INV";
	SF_TRAN_CODE_CONSUME = "CONSUME";
	SF_TRAN_CODE_SCRAP = "SCRAP";
	SF_TRAN_CODE_REVERSE = "REVERSE";
	SF_TRAN_CODE_SCRIBE = "SCRIBE";

	SF_TRAN_CODE_TERMINATE = "TERMINATE";
	SF_TRAN_CODE_RECREATE = "RECREATE";
	SF_TRAN_CODE_CLEAN = "CLEAN";

	// Process Step

	SF_STEP_CREATE = 'I';
	SF_STEP_UPDATE = 'U';
	SF_STEP_DELETE = 'D';
	SF_STEP_CONFIRM = 'F';
	SF_STEP_DELETE_FORCE = 'X';
	SF_STEP_COPY = 'C';
	SF_STEP_UNDELETE = 'R';
	SF_STEP_APPROVAL = 'A';
	SF_STEP_RELEASE = 'E';
	SF_STEP_CANCEL_APPROVAL = 'P';
	SF_STEP_SCRAP = 'S';
	SF_STEP_RETURN = 'N';
	SF_STEP_REGENERATE = 'G';
	SF_STEP_VERSION_UP = 'V';
	SF_STEP_TERMINATE = 'M';

	SF_STEP_TRAN = 'T';

	// CMF Item

	// CMF
	SF_CMF_MATERIAL = "CMF_MATERIAL";
	SF_CMF_FLOW = "CMF_FLOW";
	SF_CMF_OPERATION = "CMF_OPER";
	SF_CMF_STEP = "CMF_STEP";
	SF_CMF_RESOURCE = "CMF_RESOURCE";
	SF_CMF_PORT = "CMF_PORT";

	SF_CMF_CARRIER = "CMF_CARRIER";
	SF_CMF_SUBRESOURCE = "CMF_SUBRESOURCE";
	SF_CMF_USER = "CMF_USER";
	SF_CMF_CHARACTER = "CMF_CHARACTER";
	SF_CMF_COL_SET = "CMF_COL_SET";
	SF_CMF_ORDER = "CMF_ORDER";
	SF_CMF_BOM_SET = "CMF_BOM_SET";
	SF_CMF_RECIPE = "CMF_RECIPE";
	SF_CMF_PART = "CMF_PART";
	SF_CMF_LABEL = "CMF_LABEL";

	SF_CMF_QUEUETIME = "CMF_QUEUETIME";
	SF_CMF_SERVICE = "CMF_SERVICE";

	SF_CMF_INPUT_OPER_VALUE = "CMF_INPUT_OPER_VALUE";
	
	//2012.07.03 Label CMF 추가
	SF_CMF_LABEL = "CMF_LABEL";

	// QCM CMF
	SF_CMF_SMP_PROC = "CMF_SMP_PROC";
	SF_CMF_INSP_ITEM = "CMF_INSP_ITEM";
	SF_CMF_INSP_SET = "CMF_INSP_SET";

	SF_CMF_LOT = "CMF_LOT";
	SF_CMF_SUBLOT = "CMF_SUBLOT";

	SF_CMF_TRN_ADAPT = "CMF_TRN_ADAPT";
	SF_CMF_TRN_BONUS = "CMF_TRN_BONUS";
	SF_CMF_TRN_LOSS = "CMF_TRN_LOSS";
	SF_CMF_TRN_CREATE = "CMF_TRN_CREATE";
	SF_CMF_TRN_START = "CMF_TRN_START";
	SF_CMF_TRN_END = "CMF_TRN_END";
	SF_CMF_TRN_MOVE = "CMF_TRN_MOVE";
	SF_CMF_TRN_SKIP = "CMF_TRN_SKIP";
	SF_CMF_TRN_REWORK = "CMF_TRN_REWORK";
	SF_CMF_TRN_REPAIR = "CMF_TRN_REPAIR";
	SF_CMF_TRN_REPAIR_END = "CMF_TRN_REPAIR_END";
	SF_CMF_TRN_LOCAL_REPAIR = "CMF_TRN_LOCAL_REPAIR";
	SF_CMF_TRN_SPLIT = "CMF_TRN_SPLIT";
	SF_CMF_TRN_COMBINE = "CMF_TRN_COMBINE";
	SF_CMF_TRN_MERGE = "CMF_TRN_MERGE";
	SF_CMF_TRN_HOLD = "CMF_TRN_HOLD";
	SF_CMF_TRN_RELEASE = "CMF_TRN_RELEASE";
	SF_CMF_TRN_SHIP = "CMF_TRN_SHIP";
	SF_CMF_TRN_RECEIVE = "CMF_TRN_RECEIVE";
	SF_CMF_TRN_ASSEMBLY = "CMF_TRN_ASSEMBLY";
	SF_CMF_TRN_DISASSEMBLE = "CMF_TRN_DISASSEMBLE";
	SF_CMF_TRN_REPLACE = "CMF_TRN_REPLACE";
	SF_CMF_TRN_LOTEDC = "CMF_TRN_LOTEDC";
	SF_CMF_TRN_EVENT = "CMF_TRN_EVENT";
	SF_CMF_TRN_TROUBLE = "CMF_TRN_TROUBLE";
	SF_CMF_TRN_RMA_OPEN = "CMF_TRN_RMA_OPEN";
	SF_CMF_TRN_RMA_CLOSE = "CMF_TRN_RMA_CLOSE";
	SF_CMF_TRN_SORT = "CMF_TRN_SORT";
	SF_CMF_TRN_STORE = "CMF_TRN_STORE";
	SF_CMF_TRN_UNSTORE = "CMF_TRN_UNSTORE";
	SF_CMF_TRN_TERMINATE = "CMF_TRN_TERMINATE";
	SF_CMF_TRN_CHANGE_CMF = "CMF_TRN_CHANGE_CMF";
	SF_CMF_TRN_RESERVE = "CMF_TRN_RESERVE";
	SF_CMF_TRN_UNRESERVE = "CMF_TRN_UNRESERVE";
	SF_CMF_TRN_SCRIBE = "CMF_TRN_SCRIBE";
	SF_CMF_TRN_CV = "CMF_TRN_CV";
	SF_CMF_TRN_REGENERATE = "CMF_TRN_REGENERATE";
	SF_CMF_TRN_START_STEP = "CMF_TRN_START_STEP";
	SF_CMF_TRN_END_STEP = "CMF_TRN_END_STEP";

	// change port status
	SF_CMF_TRN_CHANGE_PORT = "CMF_TRN_CHANGE_PORT";
	SF_CMF_TRN_COLLECT_LOT_DEFECT = "CMF_TRN_COLLECT_DFT";
	SF_CMF_TRN_CLEAN_LOT_DEFECT = "CMF_TRN_CLEAN_DFT";

	// Inventory CMF
	SF_CMF_TRN_IN_INV = "CMF_TRN_IN_INV";
	SF_CMF_TRN_OUT_INV = "CMF_TRN_OUT_INV";
	SF_CMF_TRN_TRANS_INV = "CMF_TRN_TRANS_INV";
	SF_CMF_TRN_CONV_TO_LOT = "CMF_TRN_CONV_TO_LOT";
	SF_CMF_TRN_CONV_TO_INV = "CMF_TRN_CONV_TO_INV";
	SF_CMF_TRN_CONSUME = "CMF_TRN_CONSUME";
	SF_CMF_TRN_SCRAP = "CMF_TRN_SCRAP";

	SF_CMF_TRN_QCM_BATCH = "CMF_TRN_QCM_BATCH";
	SF_CMF_TRN_QCM_RESULT = "CMF_TRN_QCM_RESULT";
	SF_CMF_TRN_QCM_FINAL = "CMF_TRN_QCM_FINAL";
	SF_CMF_TRN_QCM_MERGE = "CMF_TRN_QCM_MERGE";
	SF_CMF_TRN_QCM_SPLIT = "CMF_TRN_QCM_SPLIT";
	SF_CMF_CHART_SET = "CMF_CHART_SET";
	SF_CMF_CHART = "CMF_CHART";

	SF_CMF_RULE_RELATION = "CMF_RULE_RELATION";
	SF_CMF_RULE_SEQ_KEY = "CMF_RULE_SEQ_KEY";

	// Group
	SF_GRP_FLOW = "GRP_FLOW";
	SF_GRP_MATERIAL = "GRP_MATERIAL";
	SF_GRP_OPERATION = "GRP_OPER";
	SF_GRP_STEP = "GRP_STEP";
	SF_GRP_CHARACTER = "GRP_CHARACTER";
	SF_GRP_RESOURCE = "GRP_RESOURCE";
	SF_GRP_COL_SET = "GRP_COL_SET";
	SF_GRP_USER = "GRP_USER";
	SF_GRP_EVENT = "GRP_EVENT";
	SF_GRP_BOM_SET = "GRP_BOM_SET";
	SF_GRP_RECIPE = "GRP_RECIPE";
	SF_GRP_INSP_SET = "GRP_INSP_SET";
	SF_GRP_CHART = "GRP_CHART";
	SF_GRP_CHART_SET = "GRP_CHART_SET";
	
	//2012.07.03 Label GRP 추가
	SF_GRP_LABEL = "GRP_LABEL";
	
	// GCM Table Name

	// System GCM Table
	SF_GCM_MSGGRP_TBL = "MESSAGE_GROUP";

	// Collection Set Group Table 1~10
	SF_GCM_COL_GRP = "COL_GRP_";
	// acter Group Table 1~10
	SF_GCM_CHAR_GRP = "CHAR_GRP_";

	// Resource Group Table 1~10
	SF_GCM_RES_GRP = "RES_GRP_";

	// Event Group Table 1~10
	SF_GCM_EVN_GRP = "EVN_GRP_";

	// Material Group Table 1~10
	SF_GCM_MATERIAL_GRP = "MATERIAL_GRP_";

	// Flow Group Table 1~10
	SF_GCM_FLOW_GRP = "FLOW_GRP_";

	// Operation Group Table 1~10
	SF_GCM_OPER_GRP = "OPER_GRP_";

	// Step Group Table 1~10
	SF_GCM_STEP_GRP = "STEP_GRP_";

	// User Group Table 1~10
	SF_GCM_USER_GRP = "USER_GRP_";

	// BOM Set Group Table 1~10
	SF_GCM_BOM_GRP = "BOM_GRP_";

	// Recipe Group Table 1~10
	SF_GCM_RECIPE_GRP = "RECIPE_GRP_";

	// Inspection Set Group Table 1~10
	SF_GCM_INSP_SET_GRP = "INSP_SET_GRP_";

	// SPC t Group Table 1~10
	SF_GCM_CHT_GRP = "CHT_GRP_";

	// SPC t Group Table 1~10
	SF_GCM_CHTSET_GRP = "CHTSET_GRP_";
	
	//2012.07.03 Label GCM 추가
	// LABEL t Group Table 1~10
	SF_GCM_LABEL_GRP = "LABEL_GRP_";
	
	

	SF_WIP_CREATE_CODE = "CREATE_CODE";
	SF_WIP_OWNER_CODE = "OWNER_CODE";
	SF_WIP_LOT_TYPE = "LOT_TYPE";
	SF_WIP_SUBLOT_TYPE = "SUBLOT_TYPE";
	SF_WIP_MATERIAL_TYPE = "MATERIAL_TYPE";
	SF_WIP_MATERIAL_PACKTYPE = "MATERIAL_PACK_TYPE";
	SF_WIP_OPTIONAL_FLOW_GROUP = "OPTIONAL_FLOW_GROUP";
	SF_WIP_OPTIONAL_OPER_GROUP = "OPTIONAL_OPER_GROUP";

	SF_WIP_UNIT_TABLE = "UNIT";
	SF_WIP_SHIP_CODE = "SHIP_CODE";
	SF_WIP_LOSS_CODE = "LOSS_CODE";
	SF_WIP_BONUS_CODE = "BONUS_CODE";
	SF_WIP_HOLD_CODE = "HOLD_CODE";
	SF_WIP_REWORK_CODE = "REWORK_CODE";
	SF_WIP_REPAIR_CODE = "REPAIR_CODE";
	SF_WIP_RESULT_CODE = "RESULT_CODE";
	SF_WIP_ACTION_CODE = "ACTION_CODE";
	SF_WIP_RELEASE_CODE = "RELEASE_CODE";
	SF_WIP_ORDER_STATUS = "ORDER_STATUS";
	SF_WIP_TERMINATE_CODE = "TERMINATE_CODE";
	SF_WIP_CV_CODE = "CV_CODE";

	SF_WIP_LOT_DEFECT_CODE = "LOT_DEFECT_CODE";

	SF_WIP_SUBLOT_GRADE = "SUBLOT_GRADE";

	SF_INV_SCRAP_CODE = "SCRAP_CODE";

	SF_RAS_RES_TYPE = "RES_TYPE";
	SF_RAS_SUBRES_TYPE = "SUBRES_TYPE";
	SF_RAS_AREA_CODE = "AREA";
	SF_RAS_SUBAREA_CODE = "SUB_AREA";
	SF_RAS_WORK_POSITION = "WORK_POSITION";
	SF_RAS_CHAMBER_GROUP = "CHAMBER_GROUP";
	SF_RAS_PM_PERIOD = "PM_PERIOD";
	SF_RAS_PM_EVENT = "PM_EVENT";

	SF_RAS_CRR_TYPE1 = "CRR_TYPE1";
	SF_RAS_CRR_TYPE2 = "CRR_TYPE2";
	SF_RAS_CRR_TYPE3 = "CRR_TYPE3";

	SF_ATTR_TYPE_TABLE = "ATTRIBUTE_TYPE";
	
	SF_RMA_CREATE_CODE = "RMA_CREATE_CODE";
	SF_RMA_RESULT_CODE = "RMA_RESULT_CODE";
	SF_ARCHIVE_MODULE = "ARCHIVE_MODULE";
	SF_SYS_FACTORY_TYPE = "FACTORY_TYPE";
	
	// POP -> LBL
	SF_LBL_PRINTER_TYPE = "PR ER_TYPE";
	SF_LBL_RESOLUTION = "RESOLUTION";
	SF_LBL_TEXT_FONT = "TEXT_FONT";
	SF_LBL_BARCODE_FONT = "BARCODE_FONT";
	SF_LBL_PRINT_VARIABLE = "PRINT_VARIABLE";
	SF_LBL_ROTATE = "ROTATE";
	SF_GCM_CUSTOMER = "CUSTOMER";
	
	// TOOL
	SF_RAS_TOOL_STATUS = "TOOL_STATUS";
	SF_RAS_TOOL_GRP = "TOOL_GRP";
	SF_RAS_TOOL_GRADE = "TOOL_GRADE";
	SF_RAS_TOOL_DEFECT = "TOOL_DEFECT";

	// PORT
	SF_RAS_PORT_STATE = "PORT_STATE";

	// QCM
	SF_QCM_SMP_PROC_TYPE = "SMP_PROC_TYPE";
	SF_QCM_INSP_METHOD = "QCM_INSP_METHOD";
	SF_QCM_DEFECT_GRP = "QCM_DEFECT_GRP";
	SF_QCM_INSP_TYPE = "QCM_INSP_TYPE";
	SF_QCM_VENDOR = "QCM_VENDOR";
	SF_QCM_CUSTOMER = "QCM_CUSTOMER";

	//SHEET 
	SF_SHEET_QUERY_TYPE = "SHEET_QUERY_TYPE";
	SF_SHEET_SHEET_TYPE = "SHEET_SHEET_TYPE";
	SF_SHEET_DATA_TYPE = "SHEET_DATA_TYPE";
	
	// WFM
	SF_WFM_NODE_TYPE = "WFM_NODE_TYPE";

	SF_GCM_TABLE_GROUP = "GCM_TABLE_GROUP";
	SF_SEC_FUNCTION_GROUP = "FUNCTION_GROUP";
	SF_SEC_PROGRAM_LIST = "PROGRAM_LIST";

	// EDC
	SF_EDC_UNIT_TABLE = "EDC_UNIT"; // acter Unit Table

	// ID
	SF_ID_GEN_TYPE = "ID_GEN_TYPE";
	SF_ID_GEN_TRAN_CODE = "ID_GEN_TRAN_CODE";

	// Batch
	SF_BATCH_TYPE = "BATCH_TYPE";

	SF_FUNC_KEY_TYPE = "FUNC_KEY_TYPE";

	// Future Action
	SF_FAC_OA_SERVICES = "FAC_OA_SERVICES";

	SF_BIN_DATA_1 = "__BIN_DATA_1";
	SF_BIN_DATA_2 = "__BIN_DATA_2";
	SF_BIN_DATA_3 = "__BIN_DATA_3";
	SF_BIN_DATA_4 = "__BIN_DATA_4";
	SF_BIN_DATA_5 = "__BIN_DATA_5";
	SF_BIN_DATA_6 = "__BIN_DATA_6";
	SF_BIN_DATA_7 = "__BIN_DATA_7";
	SF_BIN_DATA_8 = "__BIN_DATA_8";
	SF_BIN_DATA_9 = "__BIN_DATA_9";
	SF_BIN_DATA_10 = "__BIN_DATA_10";

	// Flexible Group
	SF_SCREEN_GRP = "SCREEN_GROUP";

	// FMB
	SF_FMB_HOST_INFO = "FMB_HOST_INFO";

	// Resource Status

	// Status
	SF_RESOURCE_STATUS_WAIT = "WAIT";
	SF_RESOURCE_STATUS_PROC = "PROC";
	SF_DEFAULT_RESOURCE_STATUS = "WAIT";

	// Resource Up/Down status

	SF_RES_UP_FLAG = 'U';
	SF_RES_DOWN_FLAG = 'D';
	SF_DEFAULT_RES_UP_DOWN_FLAG = 'U';

	// Lot Status

	SF_LOT_STATUS_WAIT = "WAIT";
	SF_LOT_STATUS_PROC = "PROC";
	SF_LOT_STATUS_RESV = "RESV";

	// Attach acter to Version, Unit MAX and Value MAX

	SF_UNIT_COUNT_MAX = 500;
	SF_VALUE_COUNT_MAX = 1000;
	
	// Wran Status
	SF_WARN_STATUS = '2';

	// ToolBar and Image Index

	MESSAGE_INDEX = 34; // <<Check>> 사용하는곳이 없음
	MESSAGE_OPEN_ICON_INDEX = 51; // <<Check>> 사용하는곳이 없음
	MESSAGE_CLOSE_ICON_INDEX = 52; // <<Check>> 사용하는곳이 없음

	// Privilege Type
	SF_PRV_TYPE_RES = "RESOURCE";
	SF_PRV_TYPE_OPER = "OPERATION";
	SF_PRV_TYPE_GCMTBL = "GCMTABLE";
	SF_PRV_TYPE_SERVICE = "SERVICE";
	SF_PRV_TYPE_ATTR = "ATTRIBUTE";

	// Type
	POP_TYPE_TEXT = "T";
	POP_TYPE_BARCODE = "B";
	POP_TYPE_IMAGE = "I";
	POP_TYPE_GRAPHIC = "G";

	// Rotate
	POP_ROTATE_NORMAL = "N";
	POP_ROTATE_ROTATED = "R";
	POP_ROTATE_INVERTED = "I";
	POP_ROTATE_BOTTOMUP = "B";

	// Barcode Font
	POP_BAR_FONT_128 = "C";
	POP_BAR_FONT_3OF9 = "3";
	POP_BAR_FONT_PDF417 = "7";
	POP_BAR_FONT_EAN_8 = "8";
	POP_BAR_FONT_UPC_E = "9";
	POP_BAR_FONT_EAN_13 = "E";
	POP_BAR_FONT_UPC_A = "U";

	// Pr Port
	POP_PRINT_PORT_LPT = "LPT";
	POP_PRINT_PORT_COM = "COM";

	// Communication Value.
	STX = 0x2; // Start of Text
	ETX = 0x3; // End of Text
	CR = 0xD; // Carriage Return
	LF = 0xA; // Line Feed
	HT = 0x9; // Horizontal Tab

	// Pr Status
	s_PrtStatus = '';
	b_InputSTX = '';
	i_BufFull = 50; // Receive Buffer Full Check Count.
	s_TimeOut = "05"; // Pr Status Check-Out Timeout

	PRINT_200_DPM = 8; // Dots per Milimeter(200DPI)
	PRINT_300_DPM = 12; // Dots per Milimeter(300DPI)

	// Prompt
	PROMPT_ASCII = 'A';
	PROMPT_NUMBER = 'N';
	PROMPT_FLOAT = 'F';

	// Alarm Type
	SF_ALM_NORMAL = 'N';
	SF_ALM_RESOURCE = 'R';
	SF_ALM_AUTO_GATHER = 'A';

	// Alarm Level
	SF_ALM_LEVEL_INFO = 'I';
	SF_ALM_LEVEL_WARN = 'W';
	SF_ALM_LEVEL_ERROR = 'E';

	// Alarm Transaction Po
	SF_ALM_TRAN_START = 'S';
	SF_ALM_TRAN_SPLIT = 'P';
	SF_ALM_TRAN_END = 'E';
	SF_ALM_TRAN_REWORK = 'R';

	// QCM

	// Sampling type
	SF_QCM_SMP_TYPE_MANUAL = "MN";
	SF_QCM_SMP_TYPE_TOTAL_INSPECTION = "TI";
	SF_QCM_SMP_TYPE_FIXED_SAMPLE = "FS";
	SF_QCM_SMP_TYPE_USED_PERCENTAGE = "UP";
	SF_QCM_SMP_TYPE_USED_SCHEME = "US";

	// Inspection type
	SF_QCM_INSP_TYPE_IQC = "IQC";
	SF_QCM_INSP_TYPE_PQC = "PQC";
	SF_QCM_INSP_TYPE_OQC = "OQC";
	SF_QCM_INSP_TYPE_RMA = "RMA";

	// Inspection type
	SF_QCM_INSP_METHOD_I = "INDIVIDUAL";
	SF_QCM_INSP_METHOD_Q = "QUANTITY";

	// Final Decision
	SF_QCM_DECISION_REJECT = "REJECT";
	SF_QCM_DECISION_ACCEPT = "ACCEPT";

	// SUBLOT
	SF_SUBLOT_GOOD_GRADE = "G";
	SF_SUBLOT_SCRAP_GRADE = "S";

	SF_MFO_EXT_LOSS_TBL_DEF = "EXT_LOSS_TBL_DEF";
	SF_MFO_EXT_BONUS_TBL_DEF = "EXT_BONUS_TBL_DEF";
	SF_MFO_EXT_LOT_DEFECT_TBL = "EXT_LOT_DEFECT_TBL";

	// Archive 관련

	// 'Archive 소스 자료 삭제 여부
	ARC_SOURCE_DELETE = "D";
	ARC_SOURCE_UNDELETE = "U";

	// 'Rollback segment 사용 여부
	ARC_ROLLBACK_USE = "R";
	ARC_ROLLBACK_NOTUSE = "N";

	// 'Running archive value
	ARC_RUNNING = "Y";

	// 'Archive Backup Type
	ARC_BACKUP_FILE = "F";
	ARC_BACKUP_DB = "D";
	ARC_BACKUP_FILE_DB = "B";

	// Admin 관련

	SF_AUTO_REFRESH_TIME = 30; // Auto Refresh Time (Sec)

	// '서버 모니터링시 서버로부터 응답상태를 나타냄
	ADM_IDLE_STATUS = 0; // IDLE 상태
	ADM_REQUEST_STATUS = 1; // 서버에 요청을 한상태
	ADM_REPLY_STATUS = 2; // 서버로부터 응답을 받음

	// '최대 Request 갯수
	ADM_MAX_REQUEST_CNT = 1000;

	// 'GCM Table List
	SF_GCM_SERVER_LIST = "SERVER_LIST";

	SF_LOCAL_HOST = "LOCALHOST";
	SF_DEFAULT_IP = "DEFAULT";

	// Attribute Type
	SF_ATTR_TYPE_LOT = "LOT";
	SF_ATTR_TYPE_RESOURCE = "RESOURCE";
	SF_ATTR_TYPE_SUBLOT = "SUBLOT";
	SF_ATTR_TYPE_BOM = "BOM";
	SF_ATTR_TYPE_MATERIAL = "MATERIAL";
	SF_ATTR_TYPE_FLOW = "FLOW";
	SF_ATTR_TYPE_OPER = "OPER";
	SF_ATTR_TYPE_FACTORY = "FACTORY";
	SF_ATTR_TYPE_CARRIER = "CARRIER";

	// CONVERT TYPE

	SF_CONVERT_DATE_FORMAT = "DATE"; // "yyyyMMdd" Format
	SF_CONVERT_HYPHENDATE_FORMAT = "HYPHENDATE";// "yyyy-MM-dd" Format
	SF_CONVERT_HYPHENDATETIME_FORMAT = "HYPHENDATETIME";// "yyyy-MM-dd" Format
	SF_CONVERT_SLASHDATE_FORMAT = "SLASHDATE"; // "yyyy/MM/dd" Format
	SF_CONVERT_NODAYDATE_FORMAT = "NODAYDATE"; // "yyyyMM Format for monthly report
	SF_CONVERT_TIME_FORMAT = "TIME"; // "HHmmss" Format
	SF_CONVERT_DATETIME_FORMAT = "DATETIME"; // "yyyyMMddHHmmss" Format
	SF_CONVERT_YEAR_FORMAT = "YEAR"; // "yyyy" Format
	SF_CONVERT_MONTH_FORMAT = "MONTH"; // "MM" Format

	// ETC  ant

	EXCEL_MAX_COL = 255;
	SF_MAX_SLOT_CNT = 1000;
	SF_MAX_BATCH_CNT = 12;

	SF_SYS_DOCK_MENU = "SYS_MENU_MENU";
	SF_SYS_DOCK_FAVORITES = "SYS_MENU_FAVORITES";
	SF_SYS_DOCK_OPERATION = "SYS_MENU_OPERATION";
	SF_SYS_DOCK_RESOURCE = "SYS_MENU_RESOURCE";
	SF_SYS_DOCK_DISPATCHER = "SYS_MENU_DISPATCHER";
	SF_SYS_DOCK_WORKFLOW = "SYS_MENU_MODELER";
	SF_SYS_DOCK_BBS = "SYS_MENU_BBS";
	SF_SYS_DOCK_FMB = "SYS_MENU_FMB";

	//   FONT_NAME
	//   FONT_SIZE As Single = 9.0

	SP_MAX_COLUMN_WIDTH = 500;
	SP_MIN_COLUMN_WIDTH = 20;

	LV_MAX_COLUMN_WIDTH = 500;
	LV_MIN_COLUMN_WIDTH = 50;
	LV_MAX_LIST_COUNT = 20;
	LV_BONUS_LISTVIEW_HEIGHT = 2;
	LV_BONUS_COLUMN_WIDTH = 4;
	LV_BONUS_COLUMN_WIDTH_WITH_IMAGE = 2;

	SF_MAX_QTY = 9999999.999; // Max Qty
	SF_MIN_QTY = -9999999.999; // Min Qty

	SF_DONT_CHECK_PASSWORD = "DO_NOT_CHECK_PASSWORD";

	SF_MAX_GDI_COUNT = 8000;
	
	/* web에서 정의한 상수정의 */
	SF_MAX_INT = Math.pow(2, 31) - 1; //C# max_int 2147483647이므로 -1
	
	
	//MPGC
	SF_SHEET_EVENT = "SHEET_EVENT";
	SF_SUCCESS_STATUS = "0";
	SF_FAIL_STATUS = "1";
	SF_TRBL_STATUS = "3";
	
	//SPC
	SF_SPC_MAX_VALUE = 9999999999; // Max Qty
	SF_SPC_MIN_VALUE = -9999999999; // Min Qty
	SF_SPC_ACTION_CODE = "SPC_ACTION_CODE";
    SF_SPC_TROUBLE_CODE = "SPC_TROUBLE_CODE";
    
    SF_STEP_PEND = 'P';
    SF_STEP_CONT = 'N';
	
	return {};
}());