T({
	Caption : {
		Other : {
			"1 point beyond 3 sigma (OOC)" : "점이 관리한계를 벗어난 경우(OOC)",
			"14 consecutive points increasing or decreasing" : "14점 이상 연속적으로 상승하거나 하강하는 경우",
			"15 consecutive points between plus 1 sigma and minus 1 sigma" : "15점 이상 1시그마 안에 존재하는 경우",
			"2 out of 3 consecutive points beyond 2 sigma" : "3점 중 2점이 2시그마 이상 벗어난 경우",
			"4 out of 5 consecutive points beyond 1 sigma" : "5점 중 4점이 1시그마 이상 벗어난 경우",
			"7 consecutive points above the CL" : "중심선(CL)을 기준으로 위로 연속 7점 이상인 경우",
			"7 consecutive points below the CL" : "중심선(CL)을 기준으로 아래로 연속 7점 이상인 경우",
			"7 consecutive points decreasing" : "7점 이상 연속적으로 하강하는 경우",
			"7 consecutive points increasing" : "7점 이상 연속적으로 상승하는 경우",
			"8 consecutive points beyond plus 1 sigma and minus 1 sigma" : "8점 이상이 1시그마 밖에 존재하는 경우",
			"8 consecutive points same side of average" : "중심선(CL)을 기준으로 위, 혹은 아래로 8점 이상이 연속적으로 존재하는 경우",
			"100% Inspection" : "100% 검사",
			"Above" : "바코드 위 문자",
			"Ack Flag" : "확인 여부",
			"Ack Time" : "확인 시간",
			"Ack User" : "확인 사용자",
			"Action Backcolor" : "PM 실행별 바탕색",
			"Action Code" : "조치 코드",
			"Action Comment" : "조치 주석",
			"Action Time" : "조치 시간",
			"Action User" : "조치자",
			"Active Status" : "활성 상태",
			"Adapt Lot" : "Lot 특성 변경",
			"Add in the tool bar" : "툴바에 추가",
			"Alarm" : "알람",
			"Alarm Action" : "알람 동작",
			"Alarm Code" : "알람 코드",
			"Alarm Flag" : "알람 여부",
			"Alarm ID" : "알람",
			"Alarm Information" : "알람 정보",
			"Alarm Level" : "알람 레벨",
			"Alarm Message" : "알람 메시지",
			"Alarm Msg ID" : "알람 메시지",
			"Alarm Resource Setup" : "알람 장비 셋업",
			"Alarm Set Flag" : "현재 알람 발생",
			"Alarm Type" : "알람 타입",
			"Alias" : "별명",
			"All" : "전체",
			"All Chart Calculation" : "모든 차트 계산",
			"All Chart List" : "모든 차트 목록",
			"All Data" : "모든 데이타",
			"All Event List" : "모든 이벤트 목록",
			"All Item Preview" : "모두 미리보기",
			"All Operation List" : "모든 공정 목록",
			"All Resource List" : "모든 자원 목록",
			"All Tool" : "모든 툴",
			"All Tool Event List" : "모든 툴 이벤트 목록",
			"All Tool List" : "모든 툴 목록",
			"All User List" : "모든 사용자 목록",
			"Alloc Qty" : "할당 수량",
			"Alt End Flow" : "개조 마지막 플로우",
			"Alt End Oper" : "개조 마지막 공정",
			"Alt Flag" : "개조 여부",
			"Alt Mat Flag" : "제품 변경 가능",
			"Alt Ret Flow" : "개조 반환 플로우",
			"Alt Ret Oper" : "개조 반환 공정",
			"Alt Return Flow" : "개조 반환 플로우",
			"Alt Return Oper" : "개조 반환 공정",
			"Alter End Flow" : "개조 마지막 플로우",
			"Alter End Oper" : "개조 마지막 공정",
			"Alter Flag" : "개조 여부",
			"Alter Information" : "개조 정보",
			"Alter Ret Flow" : "개조 반환 플로우",
			"Alter Ret Oper" : "개조 반환 공정",
			"Alter Return Flow" : "개조 반환 플로우",
			"Alter Return Oper" : "개조 반환 공정",
			"Apply Current Chart Period" : "현재 차트의 기간 적용",
			"Apply End Time" : "적용 만료 시간",
			"Apply Start Time" : "적용 시작 시간",
			"Apply Time" : "적용 시간",
			"Approval" : "승인",
			"Approval and Release" : "승인 및 배포",
			"Approval and Release BOM Set Version" : "BOM 승인 및 배포",
			"Approval and Release Collection Set Version" : "콜랙션 셋 승인 및 배포",
			"Approval and Release Recipe Version" : "레서피 승인 및 배포",
			"Approval Flag" : "승인 여부",
			"Approval Information" : "승인 정보",
			"Approval Require Flag" : "승인 필요",
			"Approval Time" : "승인 시간",
			"Approval User" : "승인 사용자",
			"Area" : "에어리어",
			"Area ID" : "에어리어",
			"Ascii" : "문자",
			"Ascii Data" : "문자 데이터",
			"Assembly File" : "Assembly 파일",
			"Assembly Lot" : "조립",
			"Assembly Name" : "Assembly 이름",
			"Attach Character to Version" : "콜랙션 셋 버전에 캐릭터 등록",
			"Attach Chart to MFO" : "차트 MFO 셋업",
			"Attach Collection Set to MFO" : "콜랙션 셋 MFO 셋업",
			"Attach File 1" : "첨부 파일 1",
			"Attach File 2" : "첨부 파일 2",
			"Attach File 3" : "첨부 파일 3",
			"Attach File 4" : "첨부 파일 4",
			"Attach File 5" : "첨부 파일 5",
			"Attach Flow" : "플로우 부여",
			"Attach Function" : "기능 부여",
			"Attach Lot To Order" : "생산 지시 - Lot 연결",
			"Attach Material to Version" : "BOM Set Version에 제품 등록",
			"Attach Operation" : "공정 부여",
			"Attach Qty" : "투입 수량",
			"Attach Recipe To MFO" : "레서피 MFO 셋업",
			"Attach Resource" : "자원 부여",
			"Attach User to Chart" : "차트 사용자 셋업",
			"Attached Chart List" : "지정된 차트 목록",
			"Attached Flow" : "부여된 플로우",
			"Attached Function" : "부여된 기능",
			"Attached Label" : "할당된 라벨",
			"Attached Operation" : "부여된 공정",
			"Attached Resource" : "부여된 자원",
			"Attached Tool" : "부여된 툴",
			"Attached Tool Event" : "부여된 툴 이벤트",
			"Attached User List" : "지정된 사용자 목록",
			"Attribute Information" : "속성 정보",
			"Attribute Key" : "속성 키",
			"Attribute Lot" : "Lot 속성 변경",
			"Attribute Name" : "속성 이름",
			"Attribute Type" : "속성 타입",
			"Auto Calculation" : "자동 계산",
			"Auto Calculation Control Limit" : "관리선 자동 계산",
			"Auto Control Limit" : "관리선 자동 계산",
			"Auto Control Limit Calculation Flag" : "자동 관리선 계산",
			"Auto Input Flag" : "자동 입력",
			"Auto Refresh" : "자동 갱신",
			"Auto Release" : "자동 배포",
			"Auto. Final Decision" : "자동 최종 판정",
			"Available Function" : "사용 가능한 기능",
			"Available Function List" : "사용가능한 기능 목록",
			"Available Label" : "사용가능한 라벨",
			"Average" : "평균",
			"Background Image" : "배경 이미지",
			"Bar Height" : "바의 높이",
			"Bar Rate" : "바의 비율",
			"Bar Width" : "바의 폭",
			"Barcode Font" : "바코드 글꼴",
			"Base Material" : "기본 제품",
			"Based on Time" : "시간 별 조회",
			"Batch Condition" : "묶음 조건",
			"Batch Count" : "묶음 개수",
			"Batch ID" : "묶음 ID",
			"Batch Seq" : "묶음 Seq",
			"Bay ID" : "베이",
			"BCR Status" : "바코드 상태",
			"Below" : "바코드 아래 문자",
			"Birthday" : "생년월일",
			"Blank Save" : "공백 저장 가능",
			"Blank Save Flag" : "공백 저장 가능",
			"BOM Hist Seq" : "BOM 이력 Seq",
			"BOM Hist Type" : "BOM 이력 타입",
			"BOM Set ID" : "BOM Set ID",
			"BOM Set Setup" : "BOM Set 셋업",
			"BOM Set Version" : "BOM Set 버전",
			"Bonus" : "보상",
			"Bonus Code" : "보상 코드",
			"Bonus Comment" : "보상 주석",
			"Bonus Information" : "보상 정보",
			"Bonus Lot" : "Lot 보상",
			"Bonus Table" : "보상 테이블",
			"Bonus Type Flag" : "보상 타입",
			"C_Material" : "자식 제품",
			"Calculation End Time" : "계산 완료 시간",
			"Calculation Start Time" : "계산 시작 시간",
			"Calendar ID" : "캘린더 ID",
			"Calendar Setup" : "캘린더 셋업",
			"Calendar Setup (Detail)" : "캘린더 상세 셋업",
			"Calendar Type" : "캘린더 타입",
			"Capability Analysis" : "공정능력 분석",
			"Capability Index" : "공정능력지수",
			"Carrier" : "캐리어",
			"Carrier ID" : "캐리어 ID",
			"Carrier Type" : "캐리어 타입",
			"Carrier Type1" : "캐리어 타입1",
			"Carrier Type2" : "캐리어 타입2",
			"Carrier Type3" : "캐리어 타입3",
			"Cause Flow" : "원인 플로우",
			"Cause Oper" : "원인 공정",
			"Cause Operation" : "원인 공정",
			"Cause Res ID" : "원인 자원",
			"Cause Resource" : "원인 자원",
			"Cell [X,Y,Z] " : "셀 [X,Y,Z]",
			"Cell Count [X,Y,Z]" : "셀 개수 [X,Y,Z]",
			"Cell Count X" : "셀 개수(X좌표)",
			"Cell Count Y" : "셀 개수(Y좌표)",
			"Cell Count Z" : "셀 개수(Z좌표)",
			"Cell Size [X,Y,Z]" : "셀 크기 [X,Y,Z]",
			"Cell Size X" : "셀 크기(X좌표)",
			"Cell Size Y" : "셀 크기(Y좌표)",
			"Cell Size Z" : "셀 크기(Z좌표)",
			"Central Flag" : "기준 공장 정보",
			"Chamber Dependent Flag" : "챔버 종속 여부",
			"Chamber Group" : "챔버 그룹",
			"Change EDC Data" : "EDC 데이터 변경",
			"Change Flag" : "변경 여부",
			"Change Flag1" : "Change Flag1",
			"Change Flag10" : "Change Flag10",
			"Change Flag2" : "Change Flag2",
			"Change Flag3" : "Change Flag3",
			"Change Flag4" : "Change Flag4",
			"Change Flag5" : "Change Flag5",
			"Change Flag6" : "Change Flag6",
			"Change Flag7" : "Change Flag7",
			"Change Flag8" : "Change Flag8",
			"Change Flag9" : "Change Flag9",
			"Change Item" : "변경 항목",
			"Change Lot Data" : "Lot Data 변경",
			"Change Password" : "암호 변경",
			"Change Password Flag" : "암호 변경 가능",
			"Change Resource Data" : "자원 데이터 변경",
			"Change Status" : "상태 변경",
			"Change Status 1" : "상태 변경 1",
			"Change Status 10" : "상태 변경 10",
			"Change Status 2" : "상태 변경 2",
			"Change Status 3" : "상태 변경 3",
			"Change Status 4" : "상태 변경 4",
			"Change Status 5" : "상태 변경 5",
			"Change Status 6" : "상태 변경 6",
			"Change Status 7" : "상태 변경 7",
			"Change Status 8" : "상태 변경 8",
			"Change Status 9" : "상태 변경 9",
			"Change Status1" : "Change Status1",
			"Change Status10" : "Change Status10",
			"Change Status2" : "Change Status2",
			"Change Status3" : "Change Status3",
			"Change Status4" : "Change Status4",
			"Change Status5" : "Change Status5",
			"Change Status6" : "Change Status6",
			"Change Status7" : "Change Status7",
			"Change Status8" : "Change Status8",
			"Change Status9" : "Change Status9",
			"Change Up Down" : "Up Down 변경",
			"Change Up Down Flag" : "Up Down 변경 여부",
			"Change Up/Down" : "Up/Down 변경",
			"Change Up/Down Flag" : "Up/Down 변경 여부",
			"Change Value" : "변경값",
			"Char Desc" : "캐릭터 설명",
			"Char ID" : "캐릭터",
			"Character" : "캐릭터",
			"Character Group" : "캐릭터 그룹",
			"Character ID" : "캐릭터 ID",
			"Character Seq" : "캐릭터 Seq",
			"Character Setup" : "캐릭터 셋업",
			"Chart" : "차트",
			"Chart Desc" : "차트 설명",
			"Chart Flag" : "차트 플래그",
			"Chart ID" : "차트 ID",
			"Chart Information" : "차트 정보",
			"Chart Options" : "차트 옵션",
			"Chart Set" : "차트 셋",
			"Chart Set ID" : "차트 셋",
			"Chart Set Setup" : "차트 셋 셋업",
			"Chart Setup" : "차트 셋업",
			"Check Digit" : "체크 문자 인쇄",
			"Check Field" : "체크 필드",
			"Check Flag" : "체크 여부",
			"Check Flag1" : "Check Flag1",
			"Check Flag10" : "Check Flag10",
			"Check Flag2" : "Check Flag2",
			"Check Flag3" : "Check Flag3",
			"Check Flag4" : "Check Flag4",
			"Check Flag5" : "Check Flag5",
			"Check Flag6" : "Check Flag6",
			"Check Flag7" : "Check Flag7",
			"Check Flag8" : "Check Flag8",
			"Check Flag9" : "Check Flag9",
			"Check Item" : "체크 항목",
			"Check Qty" : "수량 체크",
			"Check Security Operation" : "권한 체크",
			"Check Status" : "상태 체크",
			"Check Status1" : "Check Status1",
			"Check Status10" : "Check Status10",
			"Check Status2" : "Check Status2",
			"Check Status3" : "Check Status3",
			"Check Status4" : "Check Status4",
			"Check Status5" : "Check Status5",
			"Check Status6" : "Check Status6",
			"Check Status7" : "Check Status7",
			"Check Status8" : "Check Status8",
			"Check Status9" : "Check Status9",
			"Check Up Down" : "Up Down 체크",
			"Check Up Down Flag" : "Up Down 체크 여부",
			"Check Up/Down" : "Up/Down 체크",
			"Check Up/Down Flag" : "Up/Down 체크 여부",
			"Check User ID 1" : "체크 사용자 1",
			"Check User ID 2" : "체크 사용자 2",
			"Check User ID 3" : "체크 사용자 3",
			"Check Value" : "체크값",
			"Chg Qty" : "변환 수량",
			"Child -> Parent" : "자식 -> 부모",
			"Oper Name" : "공정 이름",
			"Split/Merge" : "분리/결합",
			"View Info" : "조회 정보",
			"Child Lot" : "분리 Lot",
			"Child Lot ID" : "분리 Lot ID",
			"Child Lot Infomation" : "분리 Lot 정보",
			"Chk Serial Flag" : "시리얼 체크",
			"Class" : "종류",
			"Clean Count" : "세정 횟수",
			"Clean Defect Data" : "결함 제거",
			"Clean Flag" : "결함 제거 여부",
			"Clean Hist Seq" : "결함 제거 이력 Seq",
			"Clean Limit" : "세정 가능 횟수",
			"Clean Time" : "결함 제거 시간",
			"Clean User ID" : "결함 제거자",
			"Cleaned" : "제거된 데이타",
			"Clear Alarm" : "알람 초기화",
			"Clear Change Status 1" : "초기화 상태 변경 1",
			"Clear Change Status 10" : "초기화 상태 변경 10",
			"Clear Change Status 2" : "초기화 상태 변경 2",
			"Clear Change Status 3" : "초기화 상태 변경 3",
			"Clear Change Status 4" : "초기화 상태 변경 4",
			"Clear Change Status 5" : "초기화 상태 변경 5",
			"Clear Change Status 6" : "초기화 상태 변경 6",
			"Clear Change Status 7" : "초기화 상태 변경 7",
			"Clear Change Status 8" : "초기화 상태 변경 8",
			"Clear Change Status 9" : "초기화 상태 변경 9",
			"Clear Comment" : "초기화 주석",
			"Clear Event" : "초기화 이벤트",
			"Clear Event Flag" : "초기화 이벤트 발생 여부",
			"Clear Flag" : "초기화 여부",
			"Clear Login Fail Count" : "로그인 실패 횟수 초기화",
			"Clear Lot Alarm" : "Lot 알람 초기화",
			"Clear Old Password" : "이전 암호 초기화",
			"Clear Res Comment" : "초기화 장비 주석",
			"Clear Resource Alarm" : "장비 알람 초기화",
			"Clear SPC Alarm" : "SPC 알람 초기화",
			"Clear Time" : "초기화 시간",
			"Clear User" : "초기화 사용자",
			"Close Information" : "반송 처리 정보",
			"Close Return Lot" : "반송 Lot 처리",
			"CMF Setup" : "사용자 정의 셋업",
			"Coat PP ID" : "Coat PP ID",
			"Code" : "코드",
			"Code Data Setup" : "코드 데이타 셋업",
			"Code Table Setup" : "코드 테이블 셋업",
			"Col Set Desc" : "콜랙션 셋 설명",
			"Col Set ID" : "콜랙션 셋",
			"Col Set Version" : "Col Set 버전",
			"Collect Defect Data" : "결함 데이터 수집",
			"Collect EDC Data by Chart Set" : "차트 셋 EDC 데이터 수집",
			"Collect Lot Data" : "Lot Data 수집",
			"Collect Lot Data by Chart Set (Type 1)" : "차트 셋 Lot 데이터 수집 (Type 1)",
			"Collect Lot Data by Chart Set (Type 2)" : "차트 셋 Lot 데이터 수집 (Type 2)",
			"Collect Lot Data by Chart Set (Type 3)" : "차트 셋 Lot 데이터 수집 (Type 3)",
			"Collect Resource Data" : "자원 데이터 수집",
			"Collect Resource Data by Chart Set (Type 1)" : "차트 셋 장비 데이터 수집 (Type 1)",
			"Collect Resource Data by Chart Set (Type 2)" : "차트 셋 장비 데이터 수집 (Type 2)",
			"Collect Resource Data by Chart Set (Type 3)" : "차트 셋 장비 데이터 수집 (Type 3)",
			"Collection Set" : "콜랙션 셋",
			"Collection Set Group" : "콜랙션 셋 그룹",
			"Collection Set ID" : "콜랙트 Set ID",
			"Collection Set Setup" : "콜랙션 셋 셋업",
			"Collection Set Version" : "콜랙션 셋 버전",
			"Column Count" : "행의 수",
			"Combine Lot" : "Lot 결합",
			"Command" : "명령어",
			"Comment" : "주석",
			"Comment1" : "주석 1",
			"Comment2" : "주석 2",
			"Comment3" : "주석 3",
			"Comments" : "주석",
			"COMPLETED" : "완료",
			"Confirm Password" : "확인 암호",
			"Consume" : "자재 사용",
			"Consume Qty" : "사용 수량",
			"Control Mode" : "콘트롤 모드",
			"Control Name" : "콘트롤 이름",
			"Control Name 1" : "콘트롤 1",
			"Control Name 10" : "콘트롤 10",
			"Control Name 2" : "콘트롤 2",
			"Control Name 3" : "콘트롤 3",
			"Control Name 4" : "콘트롤 4",
			"Control Name 5" : "콘트롤 5",
			"Control Name 6" : "콘트롤 6",
			"Control Name 7" : "콘트롤 7",
			"Control Name 8" : "콘트롤 8",
			"Control Name 9" : "콘트롤 9",
			"Controls" : "콘트롤",
			"Convert Inventory To Lot" : "자재에서 Lot으로 변환",
			"Convert Lot To Inventory" : "Lot에서 자재로 변환",
			"Convert Qty" : "변환 수량",
			"Convert Qty 1" : "변환 수량 1",
			"Convert Qty 2" : "변환 수량 2",
			"Convert Qty 3" : "변환 수량 3",
			"Copy" : "복사",
			"Copy Collection Set" : "콜렉션 셋 복사",
			"Copy Dispatcher" : "디스페쳐 복사",
			"Copy Flow" : "플로우 복사",
			"Copy Label" : "라벨 복사",
			"Copy Privilege Group" : "권한 그룹 복사",
			"Copy Security Group" : "보안 그룹 복사",
			"Copy Table" : "테이블 복사",
			"Copy Version" : "버전 복사",
			"Create CMF" : "생성 사용자 정의 필드",
			"Create Code" : "생성 코드",
			"Create Comment" : "생성 주석",
			"Create Customized Field" : "생성시의 사용자 정의 필드",
			"Create Future Action" : "Future Action 생성",
			"Create Info" : "생성 정보",
			"Create Lot" : "Lot 생성",
			"Create Lot Based On Order" : "생산 지시에 의한 Lot 생성",
			"Create Lot Based On Plan" : "생산 계획에 의한 Lot 생성",
			"Create Lot Count" : "생성 Lot 개수",
			"Create Lot Information" : "Lot 생성 정보",
			"Create Planned Lot" : "계획된 Lot 생성",
			"Create Qty" : "생성 수량",
			"Create Qty 1" : "생성 수량 1",
			"Create Qty 1/2/3" : "생성 수량 1/2/3",
			"Create Qty 2" : "생성 수량 2",
			"Create Qty 3" : "생성 수량 3",
			"Create Queue Time" : "Queue Time 생성",
			"Create Status" : "생성 상태",
			"Create Time" : "생성 시간",
			"Create Transaction Customized Field" : "Lot 생성 사용자 정의 필드",
			"Create User" : "생성 사용자",
			"Create User ID" : "생성 사용자",
			"Create User/Time" : "생성 사용자/시간",
			"Create UserID" : "생성 사용자",
			"Current Chart Calculation" : "현재 차트 계산",
			"Current Password" : "현재 암호",
			"Current Tool Status" : "현재 툴 상태",
			"Current Value" : "현재 값",
			"Custom Item" : "사용자 정의 아이템",
			"Customer" : "고객",
			"Customer ID" : "고객",
			"Customer Mat ID" : "고객 제품",
			"Customer Material" : "고객 제품",
			"Customized Field" : "사용자 정의 필드",
			"Customized Field (1~10)" : "사용자 정의 필드 (1~10)",
			"Cycle Time Setup" : "작업 시간 셋업",
			"Darkness" : "명암",
			"Data" : "데이터",
			"Data Collection Information" : "수집된 데이터 정보",
			"Date" : "날짜",
			"Day" : "요일",
			"days " : "일",
			"Day Count" : "년간 일수",
			"Days Per Week" : "주간 근무일",
			"Default INV Operation" : "자재 입고 공정",
			"Default Qty 1" : "투입 수량 1",
			"Default Qty 2" : "투입 수량 2",
			"Default Qty 3" : "투입 수량 3",
			"Default Unit" : "기본 단위 사용",
			"Default Unit Flag" : "기본 단위 사용",
			"Default Unit Ovr" : "기본 단위 무시",
			"Default Unit Override Flag" : "기본 단위 무시",
			"Default Value" : "기본 값",
			"Defect Clean Count" : "제거된 툴 결함 개수",
			"Defect Code " : "결함 코드",
			"Defect Collect Count" : "툴 결함 개수",
			"Defect Count" : "결점수",
			"Defect Group" : "결점 그룹",
			"Defect Qty" : "결점 수량",
			"Delete BOM History" : "BOM 이력 삭제",
			"Delete Comment" : "삭제 주석",
			"Delete Flag" : "삭제 여부",
			"Delete Inventory History" : "자재 이력 삭제",
			"Delete Lot Data History" : "Lot 데이터 이력 삭제",
			"Delete Lot History" : "Lot 이력 삭제",
			"Delete Reason" : "삭제 이유",
			"Delete Resource Data History" : "자원 데이터 이력 삭제",
			"Delete Resource History" : "자원 이력 삭제",
			"Delete Time" : "삭제 시간",
			"Delete Tool History" : "툴 이력 삭제",
			"Delete User" : "삭제 사용자",
			"Delete User ID" : "삭제 사용자",
			"Delete User/Time" : "삭제 사용자/시간",
			"Desc" : "설명",
			"Description" : "설명",
			"Design Item" : "디자인 아이템",
			"Dimension" : "크기",
			"Dimension Height" : "높이",
			"Dimension Height Unit" : "높이 단위",
			"Dimension Horizontal" : "가로",
			"Dimension Horizontal Unit" : "가로 단위",
			"Dimension Vertical" : "세로",
			"Dimension Vertical Unit" : "세로 단위",
			"Direct Labor Count" : "주요 작업자 수",
			"Direct Labor Min" : "주요 작업 시간(분)",
			"Disable" : "사용안함",
			"Disassemble Lot" : "조립해제",
			"Dispatcher" : "디스페쳐",
			"Dispatcher" : "디스페쳐",
			"Dispatcher ID" : "디스페쳐 ID",
			"Dispatcher Setup" : "디스페쳐 셋업",
			"Display" : "알람표시",
			"Display Message" : "알람 메시지",
			"Display Precision" : "정도 표시",
			"Down Event ID" : "Down 이벤트",
			"Down Hist Seq" : "Down 이력 Seq",
			"Down Interval" : "Down 간격",
			"Down Pri Sts" : "Down 최상위 상태",
			"Down Sys Tran Time" : "Down 시스템 트랜잭션 시간",
			"Down Tran Comment" : "Down 주석",
			"Down Tran Time" : "Down 트랜잭션 시간",
			"Down Tran User ID" : "Down 사용자",
			"DSP ID" : "DSP ID",
			"Due Date" : "작업 완료 일자",
			"ECC Level" : "ECC 레벨",
			"EDC Data Prompt Setup" : "EDC 데이터 문자열 셋업",
			"Email" : "이메일",
			"E-mail" : "이메일",
			"Enable" : "사용가능",
			"End Day" : "마지막 일자",
			"End Flag" : "작업종료 여부",
			"End Flow" : "마지막 플로우",
			"End Lot" : "Lot 작업 종료",
			"End Operation" : "마지막 공정",
			"End Res ID" : "작업 종료 자원",
			"End Resource ID" : "작업 종료 자원",
			"End Time" : "작업 종료 시간",
			"Engineer" : "작업자",
			"Enter Date" : "입사일",
			"ERP Interface" : "ERP와 공유",
			"Error" : "오류",
			"Error Message" : "오류 메세지",
			"Error Queue Time" : "오류 Queue Time",
			"Error User Group ID" : "오류 사용자 그룹",
			"Estimate Reason" : "추측원인",
			"Event" : "이벤트",
			"Event Action" : "이벤트 액션",
			"Event Desc" : "이벤트 설명",
			"Event Group" : "이벤트 그룹",
			"Event Group(1~10)" : "이벤트 그룹(1~10)",
			"Event ID" : "이벤트",
			"Event Setup" : "이벤트 셋업",
			"Expire Date" : "만료 날짜",
			"Fac In Time" : "공장 인 시간",
			"Factory" : "공장",
			"Factory Group (1~5)" : "공장 그룹 (1~5)",
			"Factory In Time" : "공장 인 시간",
			"Factory Setup" : "공장 셋업",
			"Factory Type" : "공장 타입",
			"Favorites" : "즐겨찾기",
			"Favorites Function List" : "즐겨찾기 기능 목록",
			"Favorites Setup" : "즐겨찾기 셋업",
			"Feed" : "용지공급",
			"Female" : "여성",
			"Field Enable All" : "모든 필드 가능",
			"Field Enable Mask" : "가능 필드 마스크",
			"Field Enable Mask Use Flag" : "필드 마스크 사용 가능",
			"Fields" : "필드",
			"File" : "이미지 이름",
			"FINDING" : "찾는중",
			"Fin Clean Flag" : "세정 완료",
			"First Day of Week" : "주의 시작 요일",
			"First Flow" : "첫번째 플로우",
			"First Half" : "상반기",
			"First Oper" : "첫번째 공정",
			"Fix Sampling Qty" : "고정 샘플링 수량",
			"Flag" : "검사 여부",
			"Flow" : "플로우",
			"Flow Desc" : "플로우 설명",
			"Flow Description" : "플로우 설명",
			"Flow Group (1~10)" : "플로우 그룹 (1~10)",
			"Flow In Time" : "플로우 인 시간",
			"Flow Match" : "플로우 매치",
			"Flow Setup" : "플로우 셋업",
			"Flow-Operation" : "플로우-공정",
			"Format" : "형식",
			"Fri" : "금",
			"Friday" : "금요일",
			"From Chart ID" : "From 차트 ID",
			"From Factory" : "어느 공장",
			"From Flow" : "From 플로우",
			"From Oper" : "From 공정",
			"From Table" : "어느 테이블",
			"From To Flag" : "이동방향",
			"From To Flow" : "이동 플로우",
			"From To Hist Seq" : "이동 Lot 이력 Seq",
			"From To Lot ID" : "이동 Lot ID",
			"From To Mat ID" : "이동 제품",
			"From To Oper" : "이동 공정",
			"From To Qty" : "이동 수량",
			"From To Qty 1" : "이동 수량 1",
			"From To Qty 1/2/3" : "이동 수량 1/2/3",
			"From To Qty 2" : "이동 수량 2",
			"From To Qty 3" : "이동 수량 3",
			"From Version" : "From 버전",
			"Function" : "기능",
			"Function Desc" : "기능 설명",
			"Function Group" : "기능 그룹",
			"Function Name" : "기능 이름",
			"Function Setup" : "기능 셋업",
			"Function Type" : "기능 타입",
			"Future Action Setup" : "Future Action 셋업",
			"Gather Alarm Flag" : "알람 수집 가능",
			"GCM Table1" : "GCM Table1",
			"GCM Table10" : "GCM Table10",
			"GCM Table2" : "GCM Table2",
			"GCM Table3" : "GCM Table3",
			"GCM Table4" : "GCM Table4",
			"GCM Table5" : "GCM Table5",
			"GCM Table6" : "GCM Table6",
			"GCM Table7" : "GCM Table7",
			"GCM Table8" : "GCM Table8",
			"GCM Table9" : "GCM Table9",
			"General" : "일반",
			"General 1" : "일반 1",
			"General 2" : "일반 2",
			"General 3" : "일반 3",
			"General Code Data Setup" : "General Code Data 셋업",
			"General Code Table Setup" : "General Code Table 셋업",
			"Grade" : "등급",
			"Graph Type" : "그래프 종류",
			"Graphic Height" : "그래픽 높이",
			"Graphic Thick" : "그래픽 두께",
			"Graphic Width" : "그래픽 폭",
			"Gross" : "총중량",
			"Group" : "그룹",
			"Group 1" : "그룹 1",
			"Group 2" : "그룹 2",
			"Group 3" : "그룹 3",
			"Group 4" : "그룹 4",
			"Group 5" : "그룹 5",
			"Group 6" : "그룹 6",
			"Group 7" : "그룹 7",
			"Group 8" : "그룹 8",
			"Group 9" : "그룹 9",
			"Group 10" : "그룹 10",
			"Group Definition" : "그룹 정의",
			"Group Item" : "그룹 아이템",
			"Group Prompt" : "그룹 문자열",
			"Group Prompt" : "그룹 문자열",
			"Group Prompt (1~10)" : "그룹 문자열 (1~10)",
			"Group Setup" : "그룹 셋업",
			"Height" : "높이",
			"Height Unit" : "높이 단위",
			"Help Url" : "도움말 주소",
			"High error" : "문제 상한값",
			"High error" : "문제 상한값",
			"High Warning" : "경고 상한값",
			"High Warning" : "경고 상한값",
			"Hist Del Flag" : "이력 삭제 여부",
			"Hist Del Time" : "이력 삭제 시간",
			"Hist Del User ID" : "이력 삭제 사용자",
			"Hist Delete Comment" : "이력 삭제 주석",
			"Hist Delete Flag" : "이력 삭제 여부",
			"Hist Delete Time" : "이력 삭제 시간",
			"Hist Delete User ID" : "이력 삭제 사용자",
			"Hist Delete User Name" : "이력 삭제 사용자",
			"Hist Exist Flag" : "이력 존재 여부",
			"Hist Seq" : "이력 Seq",
			"Hist Start Seq" : "이력 시작 Seq",
			"Hold" : "Lot 보류",
			"Hold Code" : "보류 코드",
			"Hold Code" : "보류 코드",
			"Hold Comment" : "보류 주석",
			"Hold Flag" : "보류 여부",
			"Hold Flag/Code" : "보류 여부/코드",
			"Hold Lot" : "Lot 보류",
			"Hold Password" : "보류 암호",
			"Hold Tran Time" : "보류 트랜잭션 시간",
			"Hold User ID" : "보류 사용자",
			"Holiday" : "휴일",
			"Holiday Desc" : "휴일 설명",
			"Holyday Flag" : "휴일 여부",
			"Horizontal" : "가로",
			"Horizontal Unit" : "가로 단위",
			"Hour" : "시간",
			"Hour per Unit" : "단위당 작업시간",
			"Hours Per Day" : "일간 근무시간",
			"Image" : "이미지",
			"Image Name" : "이미지 이름",
			"Image Scale X" : "이미지 X축 확대비",
			"Image Scale Y" : "이미지 Y축 확대비",
			"Image Setup" : "이미지 셋업",
			"Print Lot Label" : "라벨 출력",
			"In Inventory" : "저장소 입고",
			"In Qty" : "입고 수량",
			"Include Completed(Released) History" : "완료되거나 해제된 이력 포함",
			"Include Created Lot" : "생성된 Lot 포함",
			"Include Delete History" : "삭제된 이력까지 포함",
			"Include Delete Resource" : "삭제된 자원 포함",
			"Include Delete Sub Resource" : "삭제된 서브 자원 포함",
			"Include Deleted Chart" : "삭제된 차트 포함",
			"Include Deleted History" : "삭제된 이력 포함",
			"Include Deleted Material" : "삭제된 제품 포함",
			"Include Deleted Order" : "삭제 생산지시 포함",
			"Include Excluded Data" : "제외된 데이터 포함",
			"Include Old Status" : "이전 상태 포함",
			"Include Terminated Lot" : "죽은 Lot까지 포함",
			"Include unreleased version" : "배포되지 않은 버전 포함",
			"Indirect Labor Count" : "간접 작업자 수",
			"Indirect Labor Min" : "간접 작업 시간(분)",
			"Inspection Item" : "검사 아이템",
			"Inspection Method" : "검사 방법",
			"Inspection Set" : "검사 셋",
			"Inspection Set ID" : "검사 셋",
			"Inspection Type" : "검사 종류",
			"Insp. Item" : "검사 아이템",
			"Insp. Method" : "검사 방법",
			"Insp. Set ID" : "검사 셋",
			"Insp. Set Version" : "검사 셋 버전",
			"Insp. Type" : "검사 종류",
			"Information" : "정보",
			"Inspector" : "검사자",
			"Invoice" : "송장",
			"Inv Flag" : "저장 여부",
			"INV Oper" : "저장 공정",
			"Inv Unit" : "자재 단위",
			"Inventory Flag" : "저장 여부",
			"Inventory Information" : "자재 정보",
			"Inventory Oper" : "저장 공정",
			"Inventory Operation" : "저장 공정",
			"Inventory Unit" : "자재 단위",
			"Invert" : "역 인쇄",
			"IQC" : "수입 검사",
			"IQC Flag" : "수입 검사 여부",
			"IQC Sample Flag" : "수입 샘플 검사",
			"IQC Sample Rule" : "수입 샘플 규칙",
			"Item Count" : "아이템 개수",
			"Item ID" : "아이템 ID",
			"Item Information" : "아이템 정보",
			"Item Qty" : "아이템 수량",
			"Item Serial ID" : "아이템 시리얼",
			"Julian Day" : "실제 날수",
			"Key" : "키",
			"Label" : "라벨",
			"Label Design Setup" : "라벨 디자인 셋업",
			"Label Setup" : "라벨 셋업",
			"Label(mm)" : "라벨(mm)",
			"Last Act Hist Seq" : "최근 이력 Seq",
			"Last Active Hist Seq" : "최근 이력 Seq",
			"Last Alarm ID" : "최근 알람",
			"Last Alarm Message" : "최근 알람 메시지",
			"Last Comment" : "최근 주석",
			"Last Down Time" : "최근 Down 시간",
			"Last End Time" : "최근 작업완료 시간",
			"Last Event" : "최근 이벤트",
			"Last Event Time" : "최근 이벤트 시간",
			"Last Flow" : "마지막 플로우",
			"Last Hist Seq" : "마지막 이력 Seq",
			"Last Oper" : "마지막 공정",
			"Last Start Time" : "최근 작업시작 시간",
			"Last Tool Event" : "최근 툴 이벤트",
			"Last Tran Code" : "최근 트랜잭션 코드",
			"Last Tran Time" : "최근 트랜잭션 시간",
			"Last Trans Code" : "최근 트랜잭션 코드",
			"Last Trans Time" : "최근 트랜잭션 시간",
			"Last Transaction Code" : "최근 트랜잭션 코드",
			"Last Transaction Time" : "최근 트랜잭션 시간",
			"Left" : "왼쪽",
			"Level" : "레벨",
			"Line" : "라인",
			"Loc [X,Y,Z] " : "위치 [X,Y,Z]",
			"Local Repair Lot" : "재자리 수리",
			"Location" : "위치",
			"Loss" : "손실",
			"Loss Code" : "손실 코드",
			"Loss Qty" : "손실 수량",
			"Loss Comment" : "손실 주석",
			"Loss Information" : "손실 정보",
			"Loss Lot" : "Lot 손실",
			"Loss Table" : "손실 테이블",
			"Loss Type Flag" : "손실 타입",
			"Lot Alarm Setup" : "Lot 알람 셋업",
			"Lot Assembly Information" : "Lot 조립 정보",
			"Lot Comment" : "Lot 주석",
			"Lot Create Flag" : "Lot 생성 여부",
			"Lot Create Time" : "Lot 생성 시간",
			"Lot Del Flag" : "Lot 삭제 여부",
			"Lot Del Reason" : "Lot 삭제 사유",
			"Lot Del Time" : "Lot 삭제 시간",
			"Lot Delete Flag" : "Lot 삭제 여부",
			"Lot Delete Reason" : "Lot 삭제 원인",
			"Lot Delete Time" : "Lot 삭제 시간",
			"Lot Desc" : "Lot 설명",
			"Lot History" : "Lot 이력",
			"Lot Hold" : "Lot 보류",
			"Lot Information" : "Lot 정보",
			"Lot Label Print" : "Lot 라벨 인쇄",
			"Lot List" : "Lot 목록",
			"Lot List Main" : "Lot 목록",
			"Lot Location" : "Lot 위치",
			"Lot or Res" : "Lot 또는 자원",
			"Lot or Resource" : "Lot 또는 자원",
			"Lot Priority" : "Lot 우선순위",
			"Lot Status" : "Lot 상태",
			"Lot Type" : "Lot 타입",
			"Lot/Res Count" : "Lot/자원 갯수",
			"Low error" : "문제 하한값",
			"Low Warning" : "경고 하한값",
			"Mail" : "메일",
			"Male" : "남성",
			"Margin(mm)" : "여백(mm)",
			"Mat Att Qty" : "제품 투입 수량",
			"Mat id" : "제품",
			"Mat ID" : "제품",
			"Mat Qty" : "제품 수량",
			"Mat Unit" : "제품 단위",
			"Mat_Type" : "제품 타입",
			"Material" : "제품",
			"Material Desc" : "제품 설명",
			"Mat Desc" : "제품 설명",
			"Material Group" : "제품 그룹",
			"Material Group (1~10)" : "제품 그룹 (1~10)",
			"Material ID" : "제품",
			"Material Label Setup" : "제품 라벨 셋업",
			"Material Match" : "제품 매치",
			"Material or Order" : "제품/생산지시",
			"Material Qty" : "제품 수량",
			"Material Serial" : "제품 시리얼",
			"Material Setup" : "제품 셋업",
			"Material Type" : "제품 타입",
			"Material-Flow-Operation" : "제품-플로우-공정",
			"Max Batch Qty" : "배치 최대 수량",
			"Max Batch Qty / Max Insp. Set Qty" : "배치 최대 수량 / 검사 셋 최대 수량",
			"Max Point Count" : "화면 최대점 수",
			"Max Proc" : "최대 진행 개수",
			"Max Proc Count" : "최대 진행 Lot 수",
			"Max Value" : "최대값",
			"Mean" : "평균",
			"Measure Resource ID" : "측정 자원",
			"Menu" : "메뉴",
			"Merge Lot" : "Lot 병합",
			"Message" : "메시지",
			"Message 1" : "메시지 1",
			"Message 2" : "메시지 2",
			"Message 3" : "메시지 3",
			"Message Data" : "메시지 데이터",
			"Message Group" : "메시지 그룹",
			"Message ID" : "메시지 ID",
			"Message Setup" : "메시지 셋업",
			"MFG Devision" : "생산 주체",
			"Min" : "분",
			"Min Value" : "최소값",
			"Min." : "분",
			"Modeler" : "모델러",
			"Modify Flag" : "변경 여부",
			"Modify Lot Recipe" : "Lot 레서피 변경",
			"Modify Sub Lot Recipe" : "Sub Lot 레서피 변경",
			"Mon" : "월",
			"Monday" : "월요일",
			"Month" : "달",
			"Month View" : "월 단위",
			"Move Lot" : "Lot 이동",
			"Move Qty 1" : "이동 수량 1",
			"Move Qty 2" : "이동 수량 2",
			"Move Qty 3" : "이동 수량 3",
			"Multi End Lot" : "묶음 Lot 작업 종료",
			"Multi Realtime Monitoring Control Chart" : "다중 실시간 관리도 모니터링",
			"Multi Start Lot" : "묶음 Lot 작업 시작",
			"Must Change Password At Next Login" : "다음 로그인 시 암호 변경 여부",
			"Need Clean Flag" : "세정 필요",
			"Net" : "순중량",
			"New Password" : "새로운 암호",
			"New Qty" : "새로운 수량",
			"New Qty 1" : "새 수량 1",
			"New Value" : "새 값",
			"No Result Value" : "결과 값 없음",
			"Non Periodic" : "비주기적",
			"Normal Tool" : "정상 툴",
			"Not Cleaned" : "제거되지 않은 데이타",
			"Not Print" : "숨김",
			"NSTD Flag" : "비정규 이동 여부",
			"NSTD Return Flow" : "비정규 이동 반환 플로우",
			"NSTD Return Oper" : "비정규 이동 반환 공정",
			"NSTD Time" : "비정규 이동 시간",
			"Number" : "숫자",
			"OCCURED" : "발생",
			"Old Create Code" : "이전 생성 코드",
			"Old Event" : "이전 이벤트",
			"Old Factory" : "이전 공장",
			"Old Flow" : "이전 플로우",
			"Old Hist Seq" : "이전 이력 Seq",
			"Old Lot Type" : "이전 Lot 타입",
			"Old Mat ID" : "이전 제품",
			"Old Oper" : "이전 공정",
			"Old Owner Code" : "이전 소유자 코드",
			"Old Pri Status" : "이전 최상위 상태",
			"Old Qty" : "이전 수량",
			"Old Qty 1" : "이전 수량 1",
			"Old Qty 2" : "이전 수량 2",
			"Old Qty 3" : "이전 수량 3",
			"Old Seq" : "Old Seq",
			"Old Seq" : "이전 Seq",
			"Old Tran Time" : "이전 트랜잭션 시간",
			"Old Trans Time" : "이전 트랜잭션 시간",
			"Old Up Down Flag" : "이전 Up Down 여부",
			"Only Deleted History" : "삭제된 이력만",
			"Only Down History" : "현재 Down된 이력만",
			"Only Proc Lot" : "진행중인 Lot 만",
			"OOC Count" : "이상발생 갯수",
			"OOC Type" : "이상발생 종류",
			"OOC Type2" : "이상발생 종류2",
			"OOC2 Count" : "이상발생 갯수2",
			"Open Comment" : "반송 주석",
			"Open Information" : "반송 등록 정보",
			"Open Return Lot" : "반송 Lot 등록",
			"Oper" : "공정",
			"Oper Desc" : "공정 설명",
			"Oper Description" : "공정 설명",
			"Oper In Qty 1" : "공정 인 수량 1",
			"Oper In Qty 1/2/3" : "공정 인 수량 1/2/3",
			"Oper In Qty 2" : "공정 인 수량 2",
			"Oper In Qty 3" : "공정 인 수량 3",
			"Oper In Time" : "공정 인 시간",
			"Operation" : "공정",
			"Operation Desc" : "공정 설명",
			"Operation Group" : "공정 그룹",
			"Operation Group (1~10)" : "공정 그룹 (1~10)",
			"Operation Setup" : "공정 셋업",
			"Opt" : "옵션",
			"Opt Input Flag" : "선택 입력",
			"Option" : "옵션",
			"Option Level" : "옵션 레벨",
			"Option Name" : "옵션 이름",
			"Option Name 1" : "옵션 이름 1",
			"Option Name 10" : "옵션 이름 10",
			"Option Name 2" : "옵션 이름 2",
			"Option Name 3" : "옵션 이름 3",
			"Option Name 4" : "옵션 이름 4",
			"Option Name 5" : "옵션 이름 5",
			"Option Name 6" : "옵션 이름 6",
			"Option Name 7" : "옵션 이름 7",
			"Option Name 8" : "옵션 이름 8",
			"Option Name 9" : "옵션 이름 9",
			"Optional Group" : "선택 그룹",
			"Optional Group Option" : "선택 그룹 옵션",
			"Optional Input Flag" : "선택 입력",
			"Options" : "옵션",
			"Options" : "옵션",
			"OQC" : "출하 검사",
			"OQC Flag" : "출하 검사 여부",
			"OQC Sample Flag" : "출하 샘플 검사",
			"OQC Sample Rule" : "출하 샘플 규칙",
			"Ord End Time" : "생산지시 종료 시간",
			"Ord Ship Flag" : "생산지시 출하",
			"Ord Start Time" : "생산지시 시작 시간",
			"Ord Status Flag" : "생산지시 상태",
			"Order" : "생산지시",
			"Order End Time" : "생산지시 종료 시간",
			"Order ID" : "생산지시 ID",
			"Order In Qty" : "생산지시 투입전 수량",
			"Order Information" : "생산 지시 정보",
			"Order Loss Qty" : "생산지시 손실 수량",
			"Order Out Qty" : "생산지시 투입 수량",
			"Order Qty" : "생산지시 수량",
			"Order Rwk Qty" : "생산지시 재작업 수량",
			"Order Setup" : "생산지시 셋업",
			"Order Ship Flag" : "생산지시 출하 여부",
			"Order Start Time" : "생산지시 시작 시간",
			"Order Status" : "생산지시 상태",
			"Order Status Flag" : "생산지시 상태 여부",
			"Org Due Date" : "최초 Due Date",
			"Org Due Time" : "최초 Due Time",
			"Origin X (Dots)" : "X축 원점 (Dots)",
			"Origin Y (Dots)" : "Y축 원점 (Dots)",
			"Original Due Time" : "최초 Due Time",
			"Out Inventory" : "저장소 출고",
			"Out of Spec (OOS)" : "규격한계를 벗어난 경우",
			"Out Qty" : "출고 수량",
			"Out Qty 1" : "손실 수량 1",
			"Out Qty 2" : "손실 수량 2",
			"Out Qty 3" : "손실 수량 3",
			"Owner Code" : "소유자 코드",
			"OwnerCode" : "소유자 코드",
			"Pack Lot Count" : "포장 Lot 개수",
			"Pack Qty" : "포장 수량",
			"Pack Type" : "포장 타입",
			"Page(mm)" : "페이지(mm)",
			"Parameter" : "파라미터",
			"Parameter ID" : "파라미터 ID",
			"Parent -> Child" : "부모 -> 자식",
			"Part Group" : "파트 그룹",
			"Part grp" : "파트 그룹",
			"Password" : "암호",
			"Password Change Period " : "암호 변경 주기",
			"Period" : "기간",
			"Period Flag" : "주기",
			"Period of Control Limit's Auto Calculation" : "관리선 자동 계산 주기",
			"Periodic" : "주기적",
			"Phone Home" : "집 전화",
			"Phone Mobile" : "이동 전화",
			"Phone Office" : "회사 전화",
			"Phone Other" : "그외 전화",
			"Plan Due Time" : "계획 Due Time",
			"Plan End Time" : "계획 종료 시간",
			"Plan Qty" : "계획 수량",
			"Plan Start Time" : "계획 시작 시간",
			"Plan Status" : "계획 상태",
			"Plan Terminate Time" : "예정 폐기일",
			"Planned Lot Setup" : "계획 Lot 셋업",
			"PM Information" : "PM 정보",
			"PM Part Setup" : "PM Part 셋업",
			"PM Period" : "PM 주기",
			"PM Sch Enable" : "PM Sch Enable",
			"PM Schedule Enable Flag" : "예방 정비 여부",
			"PM Schedule Setup" : "PM 스케줄 셋업",
			"PM Security" : "PM 보안",
			"PM Security Setup" : "PM 보안 셋업",
			"Point" : "점수",
			"Port Batch" : "배치 가능",
			"Port ID" : "포트 명",
			"Port Level" : "포트 우선 순위",
			"Port Sequence" : "포트 순서",
			"Port Status" : "포트 상태",
			"Port Type" : "포트 타입",
			"Point Count" : "점 갯수",
			"Position X" : "X축 위치",
			"Position Y" : "Y축 위치",
			"PP ID" : "PP ID",
			"Precision" : "소수점 자릿수",
			"Prev Active Hist Seq" : "이전 이력 Seq",
			"Previous Hist Seq" : "이전 이력",
			"Primary Change Flag" : "최상위 변경 여부",
			"Primary Change Status" : "최상위 변경 상태",
			"Primary Check Flag" : "최상위 체크 여부",
			"Primary Check Status" : "최상위 체크 상태",
			"Primary GCM Table" : "최상위 GCM 테이블",
			"Primary Status" : "최상위 상태",
			"Print" : "프린트",
			"Print Information" : "프린터 정보",
			"Print Qty" : "프린트 수량",
			"Print Speed" : "프린트 속도",
			"Printer Type" : "프린터 타입",
			"Priority" : "우선순위",
			"Privilege" : "권한",
			"Privilege Group" : "권한 그룹",
			"Privilege Group - User Relation Setup" : "권한 그룹 사용자 셋업",
			"Privilege Group Setup" : "권한 그룹 셋업",
			"Privilege Item1" : "권한 대상1",
			"Privilege Item2" : "권한 대상2",
			"Privilege Item3" : "권한 대상3",
			"Privilege Setup" : "권한 셋업",
			"Privilege Type" : "권한 유형",
			"Proc Count" : "작업진행 개수",
			"Proc Flow" : "진행 플로우",
			"Proc Lot Count" : "진행 Lot 개수",
			"Proc Mode" : "진행 모드",
			"Proc Oper" : "진행 공정",
			"Proc Res ID" : "진행 자원",
			"Proc Resource ID" : "진행 자원",
			"Proc Rule" : "진행 규칙",
			"Proc Time" : "작업 시간",
			"Process Operation" : "진행 공정",
			"Process Resource ID" : "진행 자원",
			"Process Rule" : "진행 규칙",
			"Production Order Setup" : "생산 지시 셋업",
			"Production Plan Setup" : "생산 계획 셋업",
			"Program ID" : "프로그램 ID",
			"Prompt" : "문자열",
			"Prompt 1" : "문자열 1",
			"Prompt 10" : "문자열 10",
			"Prompt 2" : "문자열 2",
			"Prompt 3" : "문자열 3",
			"Prompt 4" : "문자열 4",
			"Prompt 5" : "문자열 5",
			"Prompt 6" : "문자열 6",
			"Prompt 7" : "문자열 7",
			"Prompt 8" : "문자열 8",
			"Prompt 9" : "문자열 9",
			"Prompt Text" : "문자열 내용",
			"Properties" : "속성",
			"Publish Message" : "메시지 보내기",
			"Purchase Order" : "구매 주문",
			"PULL Operation" : "PULL 공정",
			"Qty" : "수량",
			"Qty 1" : "수량 1",
			"Qty 1/2/3" : "수량 1/2/3",
			"Qty 2" : "수량 2",
			"Qty 3" : "수량 3",
			"Qty Flag" : "수량 구분",
			"Qty1" : "수량 1",
			"Qty2" : "수량 2",
			"Qty3" : "수량 3",
			"Quarter" : "분기",
			"Queue Time" : "대기 시간",
			"Queue Time Setup" : "Queue Time 셋업",
			"R Rule Type" : "R Rule 종류",
			"RMS" : "RMS",
			"R Spec Type" : "범위 명세 타입",
			"Raise Lot Alarm" : "Lot 알람 발생",
			"Raise Resource Alarm" : "장비 알람 발생",
			"Range" : "범위",
			"Range of fluctuation beyond 3 sigma" : "변동폭이 3 sigma 이상인 경우",
			"Range of fluctuation beyond 4 sigma" : "변동폭이 4 sigma 이상인 경우",
			"Ratio(%)" : "확대비율(%)",
			"Rbar" : "R평균",
			"Realtime Monitoring Control Chart" : "실시간 관리도 모니터링",
			"Reason" : "원인",
			"Receive Group" : "수취 그룹",
			"Receive Group All" : "수취 그룹 All",
			"Receive Group Shift 1" : "수취 그룹 Shift 1",
			"Receive Group Shift 2" : "수취 그룹 Shift 2",
			"Receive Group Shift 3" : "수취 그룹 Shift 3",
			"Receive Group Shift 4" : "수취 그룹 Shift 4",
			"Receive Lot" : "Lot 수취",
			"Recipe" : "레서피",
			"Recipe Setup" : "레서피 셋업",
			"Recipe Version" : "레서피 버젼",
			"Recipe Version Setup" : "레서피 버젼 셋업",
			"Relate Hist Seq" : "관련 이력 Seq",
			"Relate Tran Code" : "관련 트랜잭션 코드",
			"Relation" : "관계",
			"Release" : "배포",
			"Release Code" : "보류해제 코드",
			"Release Comment" : "해제 주석",
			"Release Flag" : "배포 여부",
			"Release Hist Seq" : "해제 이력 Seq",
			"Release Information" : "배포 정보",
			"Release Lot" : "Lot 보류해제",
			"Release By Force" : "Lot 보류 강제 해제",
			"Release Time" : "배포 시간",
			"Release Tran Time" : "해제 트랜잭션 시간",
			"Release User" : "배포 사용자",
			"Release User ID" : "해제 사용자",
			"Release User/Time" : "배포 사용자/시간",
			"Release_bom" : "배포",
			"Release_col" : "배포",
			"Release_recipe" : "배포",
			"RELEASED" : "해제됨",
			"Released" : "배포",
			"Remote Factory" : "원격 공장",
			"Repair Code" : "수리 코드",
			"Repair End Lot" : "Lot 수리 종료",
			"Repair Flag" : "수리 여부",
			"Repair Lot" : "Lot 수리",
			"Repair Oper" : "수리 공정",
			"Repair Operation Setup" : "수리 공정 셋업",
			"Repair Return Oper" : "수리 반환 공정",
			"Replace Lot" : "대체변경",
			"Require" : "필수",
			"Res Delete Time" : "자원 삭제 시간",
			"Res Delete User" : "자원 삭제 사용자",
			"Res Desc" : "자원 설명",
			"Res ID" : "자원 ID",
			"Res Location" : "자원 위치",
			"Res Type" : "자원 타입",
			"Reserve Res ID" : "예약 자원",
			"Reserve Resource ID" : "예약 자원",
			"Resolution(DPI)" : "해상도(DPI)",
			"Resource" : "자원",
			"Resource - Event Relation" : "자원 - 이벤트 관계",
			"Resource - Event Relation Setup" : "자원 이벤트 셋업",
			"Resource - Operation Relation" : "자원 - 공정 관계",
			"Resource - Operation Relation Setup" : "자원 공정 셋업",
			"Resource - User Relation Setup" : "자원 사용자 셋업",
			"Resource Alarm Setup" : "장비 알람 셋업",
			"Resource and Etc Information" : "자원및 기타 정보",
			"Resource Comment" : "장비 주석",
			"Resource Delete Flag" : "자원 삭제 여부",
			"Resource Down" : "자원 다운",
			"Resource Group" : "자원 그룹",
			"Resource Hist Seq" : "자원 이력 Seq",
			"Resource ID" : "자원",
			"Resource Information" : "자원 정보",
			"Resource Labor Setup" : "생산 투입 인력 셋업",
			"Resource List Main" : "자원 목록",
			"Resource Setup" : "자원 셋업",
			"Resource Status" : "자원 상태",
			"Resource Status (1~10)" : "자원 상태 (1~10)",
			"Resource Type" : "자원 타입",
			"Resource Type && Etc" : "자원 타입 && 기타",
			"Result" : "결과",
			"Result Code" : "결과 코드",
			"Result Comment" : "처리 주석",
			"Result Time" : "결과 시간",
			"Result User ID" : "결과 사용자",
			"Ret Clear Flag" : "반환시 재작업 취소",
			"Reticle ID" : "레티클 ID",
			"Retire Date" : "퇴사일",
			"Return Flow" : "반환 플로우",
			"Return Oper" : "반환 공정",
			"Return Operation" : "반환 공정",
			"Return Rework Clear Flag" : "반환시 재작업 취소",
			"Returned Tool" : "반품된 툴",
			"Reverse" : "반전",
			"Rework and Alter Information" : "재작업및 개조 정보",
			"Rework and Etc Information" : "재작업및 기타 정보",
			"Rework Code" : "재작업 코드",
			"Rework Comment" : "재작업 주석",
			"Rework Count" : "재작업 횟수",
			"Rework End Flow" : "재작업 마지막 플로우",
			"Rework End Oper" : "재작업 마지막 공정",
			"Rework Flag" : "재작업 여부",
			"Rework Flag/Code" : "재작업 여부/코드",
			"Rework Flow" : "재작업 플로우",
			"Rework Flow Setup" : "재작업 플로우 셋업",
			"Rework Information" : "재작업 정보",
			"Rework Lot" : "Lot 재작업",
			"Rework Oper" : "재작업 공정",
			"Rework Ret Clear Flag" : "반환시 재작업 취소",
			"Rework Ret Flow" : "재작업 반환 플로우",
			"Rework Ret Oper" : "재작업 반환 공정",
			"Rework Return Clear Flag" : "반환시 재작업 취소",
			"Rework Return Flow" : "재작업 반환 플로우",
			"Rework Return Oper" : "재작업 반환 공정",
			"Rework Table" : "재작업 테이블",
			"Rework Time" : "재작업 시간",
			"Rotate" : "회전",
			"Row Count" : "열의 수",
			"Rule Description" : "Rule 내용",
			"Rule Setup" : "디스페쳐 규칙 셋업",
			"Rule Type" : "Rule 종류",
			"Rule Violation Action" : "Rule 위반 조치",
			"Sample Count" : "샘플 크기",
			"Sample Flag" : "샘플 검사",
			"Sample Result" : "샘플 결과",
			"Sample Rule" : "샘플 규칙",
			"Sample Size" : "샘플 크기",
			"Sample Wait Flag" : "샘플 대기",
			"Sampling Proc." : "샘플링 프로시저",
			"Sampling Procedure" : "샘플링 프로시저",
			"Sampling Rate" : "샘플링 비율",
			"Sampling Scheme" : "샘플링 개요",
			"Sampling Type" : "샘플링 타입",
			"Sat" : "토",
			"Saturday" : "토요일",
			"Sch Due Date" : "계획된 Due Date",
			"Scheduled" : "계획실행",
			"Scheduled Due Time" : "계획된 Due Time",
			"Scrap" : "자재 폐기",
			"Scrap Code" : "폐기 코드",
			"Scrap Qty" : "폐기 수량",
			"Scrapped + Returned Tool" : "폐기 또는 반품된 툴",
			"Scrapped Tool" : "폐기된 툴",
			"Sec Chk" : "보안 체크",
			"Sec." : "초",
			"Second Half" : "하반기",
			"Security Check Flag" : "보안 확인 여부",
			"Security Group" : "보안 그룹",
			"Assign Function to Security Group" : "보안 그룹에 기능 셋업",
			"Security Group Setup" : "보안 그룹 셋업",
			"Sel" : "선택",
			"Select" : "선택",
			"Select Chart" : "차트 선택",
			"Select Chart Count" : "차트 개수 선택",
			"Select Chart ID" : "차트 이름 선택",
			"Select Lot MFO" : "Lot MFO 선택",
			"Select Period" : "기간 선택",
			"Send Message" : "메시지 보내기",
			"Send To User" : "알람 발생자에게 보내기",
			"Sending Information" : "전송정보",
			"Seq" : "순번",
			"Seq." : "순번",
			"Seq Num" : "순번",
			"Serial ID" : "시리얼 ID",
			"Serial Input Flag" : "시리얼 입력",
			"Serial Seq" : "시리얼 Seq",
			"Serial Type" : "시리얼 타입",
			"Setup" : "셋업",
			"Sex" : "성별",
			"Shift" : "근무조",
			"Shift 1  Day" : "근무조 1 시작일",
			"Shift 1  Start" : "근무조 1 시작시간",
			"Shift 2  Day" : "근무조 2 시작일",
			"Shift 2  Start" : "근무조 2 시작시간",
			"Shift 3  Day" : "근무조 3 시작일",
			"Shift 3  Start" : "근무조 3 시작시간",
			"Shift 4  Day" : "근무조 4 시작일",
			"Shift 4  Start" : "근무조 4 시작시간",
			"Shifts Definition" : "근무조 정의",
			"Ship Code" : "출하 코드",
			"Ship Factory" : "출하 공장",
			"Ship Lot" : "Lot 출하",
			"Ship Operation" : "출하 공정",
			"Ship Time" : "출하 시간",
			"Shipping Factory" : "출하 공장",
			"Shipping Lot" : "출하 Lot 목록",
			"Shipping Operation" : "출하 공정",
			"Shipping Time" : "출하 시간",
			"Short Cut/ Icon" : "단축 키/ 아이콘",
			"Sigma" : "시그마",
			"Sigma (S.D.)" : "시그마(표준편차)",
			"Sigma Standard deviation" : "시그마(표준편차)",
			"Simple Chart" : "심플 차트",
			"Size" : "크기",
			"Skip Result Record" : "결과 기록 스킵",
			"Skip Result Recording" : "결과 기록 스킵",
			"SOLVING" : "해결중",
			"Sorting" : "정렬순서",
			"Sorting Type" : "정렬 순서",
			"Source Desc 1" : "소스 설명 1",
			"Source Desc 2" : "소스 설명 2",
			"Source Desc 3" : "소스 설명 3",
			"Source ID 1" : "소스 1",
			"Source ID 2" : "소스 2",
			"Source ID 3" : "소스 3",
			"Spec" : "스펙 ",
			"Spec Check Type" : "스펙 체크 종류",
			"Spec Management" : "스펙 관리",
			"Spec Out Count" : "스펙아웃 허용 수",
			"Spec Type" : "명세 타입",
			"Spec Out Unit" : "단위 명세 초과",
			"Spec Out Unit Flag" : "단위 명세 초과",
			"Split Lot" : "Lot 분리",
			"Split-Merge Lot" : "Lot 분리-병합",
			"Start Day" : "시작 일자",
			"Start Flag" : "작업시작 여부",
			"Start Lot" : "Lot 작업 시작",
			"Start Required" : "Lot 작업 시작 필요",
			"Start Res ID" : "작업 시작 자원",
			"Start Resource ID" : "작업 시작 자원",
			"Start Time" : "작업 시작 시간",
			"Status" : "상태",
			"Status Prompt" : "상태 문자열",
			"Stock Level" : "재고 등급",
			"Sub Area" : "서브 에어리어",
			"Sub Area ID" : "서브 에어리어",
			"Subcontract Flag" : "외주 생산 여부",
			"Sub Lot Tracking Flag" : "Sub Lot 추적 여부",
			"Sub Resource" : "서브 자원",
			"Sub Resource ID" : "서브 자원",
			"Sub Resource Status" : "서브 자원 상태",
			"Sub Resource Type" : "서브 자원 타입",
			"Sun" : "일",
			"Sunday" : "일요일",
			"Sys Date" : "실제 날짜",
			"System Flag" : "시스템 플래그",
			"System Table Flag" : "시스템 테이블",
			"System Tran Time" : "시스템 트랜잭션 시간",
			"Tab Page Name" : "탭 페이지 이름",
			"Tab Pages" : "탭 페이지",
			"Table" : "테이블",
			"Table Information" : "테이블 정보",
			"Table Name" : "테이블 이름",
			"Table Type" : "테이블 타입",
			"Tabpage Name 1" : "탭 페이지 1",
			"Tabpage Name 10" : "탭 페이지 10",
			"Tabpage Name 2" : "탭 페이지 2",
			"Tabpage Name 3" : "탭 페이지 3",
			"Tabpage Name 4" : "탭 페이지 4",
			"Tabpage Name 5" : "탭 페이지 5",
			"Tabpage Name 6" : "탭 페이지 6",
			"Tabpage Name 7" : "탭 페이지 7",
			"Tabpage Name 8" : "탭 페이지 8",
			"Tabpage Name 9" : "탭 페이지 9",
			"Target" : "목표",
			"Target Due Day" : "목표 생산 완료일수",
			"Target Lot ID" : "대상 Lot ID",
			"Target Lot Infomation" : "대상 Lot 정보",
			"Target Qty 1" : "목표 수량 1",
			"Target Qty 2" : "목표 수량 2",
			"Target Qty 3" : "목표 수량 3",
			"Target Yield" : "목표 생산율",
			"Terminate Flag" : "Lot 삭제",
			"Test Qty" : "테스트 수량",
			"Text Font" : "문자 글꼴",
			"Text Height" : "문자 높이",
			"Text Width" : "문자 폭",
			"Thur" : "목",
			"Thursday" : "목요일",
			"Time Information" : "시간 정보",
			"To Collection Set" : "To 콜렉션 셋",
			"To Dispatcher" : "To 디스페쳐",
			"To Factory" : "보낼 공장",
			"To Flow" : "To 플로우",
			"To INV Oper" : "To 저장 공정",
			"To Inventory" : "To 자재",
			"To Inventory Information" : "To 자재 정보",
			"To Label" : "새 라벨",
			"To Mat Att Qty" : "대체 제품 투입 수량",
			"To Material" : "To 제품",
			"To Operation" : "To 공정",
			"To Privilege Group" : "To 권한 그룹",
			"To Security Group" : "To 보안 그룹",
			"To Serial ID" : "대체 시리얼 ID",
			"To Table" : "To 테이블",
			"To Version" : "To 버전",
			"Tool" : "툴",
			"Tool - Event Relation Setup" : "툴 - 이벤트 셋업",
			"Tool Articles" : "툴 항목",
			"Tool Comment" : "주석",
			"Tool Defect Cleaning" : "툴 결함 제거",
			"Tool Defect Collection" : "툴 결함 정보 수집",
			"Tool Event" : "툴 이벤트",
			"Tool Event Setup" : "툴 이벤트 셋업",
			"Tool Group" : "툴 그룹",
			"Tool Info" : "툴 정보",
			"Tool Location" : "툴 위치",
			"Tool Set ID" : "툴셋",
			"Tool Set Location" : "툴셋 위치",
			"Tool Setup" : "툴 셋업",
			"Tool Status" : "툴 상태",
			"Tool Status Forecast " : "툴 상태 예측",
			"Tool Type" : "툴 타입",
			"Tool Type Setup" : "툴 타입 셋업",
			"Top" : "위쪽",
			"Total Count" : "총 개수",
			"Total Qty" : "총 수량",
			"Total Qty" : "수량 합",
			"Tran Code" : "트랜잭션 코드",
			"Tran Comment" : "트랜잭션 주석",
			"Tran Time" : "트랜잭션 시간",
			"Tran User ID" : "사용자",
			"Transaction Information" : "트랜잭션 정보",
			"Transaction Time" : "트랜잭션 시간",
			"Transfer Inventory" : "저장소 이동",
			"Transfer Qty" : "이동 수량",
			"Transit Flag" : "대기 여부",
			"Transit Operation" : "대기 공정",
			"TranTime" : "트랜잭션 시간",
			"Trouble/Action Code Setup" : "이상발생 / 이상조치 코드 셋업",
			"Trouble Code" : "이상발생 코드",
			"Trouble Comment" : "이상발생 주석",
			"Trouble Resource" : "자원 이상 처리",
			"Trouble Resource Information" : "이상 자원 정보",
			"Trouble Time" : "이상발생 시간",
			"Trouble User" : "이상발생자",
			"Truncate Flag" : "Truncate Flag",
			"Tues" : "화",
			"Tuesday" : "화요일",
			"type" : "타입",
			"Type Defined Field" : "툴 타입별 필드",
			"Undeleted History" : "삭제되지 않은 이력",
			"Unit" : "중량 단위",
			"Unit 1" : "단위 1",
			"Unit 2" : "단위 2",
			"Unit 3" : "단위 3",
			"Unit Base" : "단위 기반",
			"Unit Base Standard Flag" : "Unit당 Standard Time 측정",
			"Unit Count" : "단위 개수",
			"Unit Exist Flag" : "단위 존재 여부",
			"Unit ID" : "Unit ID",
			"Unit per Hour" : "시간당 단위개수",
			"Unit Seq" : "Unit Seq",
			"Unit Table" : "단위 테이블",
			"Unit Trace Flag" : "단위 추적 여부",
			"Unit1" : "개체1",
			"Unit2" : "개체2",
			"Units" : "개체",
			"Unscheduled" : "비계획실행",
			"Up Down" : "Up Down",
			"Up Down Flag" : "Up Down Flag",
			"Up Event ID" : "Up 이벤트",
			"Up Hist Seq" : "Up 이력 Seq",
			"Up Pri Sts" : "Up 최상위 상태",
			"Up Sys Tran Time" : "Up 시스템 트랜잭션 시간",
			"Up Tran Comment" : "Up 주석",
			"Up Tran Time" : "Up 트랜잭션 시간",
			"Up Tran User ID" : "Up 사용자",
			"Up/Down Flag" : "Up/Down 여부",
			"Update Future Action" : "Future Action 변경",
			"Update Information" : "수정 정보",
			"Update Queue Time" : "Queue Time 변경",
			"Update Time" : "수정 시간",
			"Update User" : "수정 사용자",
			"Update User ID" : "수정 사용자",
			"Update User/Time" : "수정 사용자/시간",
			"Update UserID" : "수정 사용자",
			"Usage Count" : "사용 횟수",
			"Usage Limit" : "사용 가능 횟수",
			"Use Alarm" : "알람 사용",
			"Use Fac" : "공장에 동일한 문자열 사용",
			"Use Fac Prt Flag" : "공장에 동일한 문자열 사용",
			"Use Factory Prompt Flag" : "공장에 동일한 문자열 사용",
			"Use Factory Prompt Flag" : "공장에 동일한 문자열 사용",
			"Use Unit" : "Unit 사용",
			"Use User Input Spec" : "스펙 사용자 입력",
			"Use User Input Size" : "구간 크기 사용자 입력",
			"User" : "사용자",
			"User Comment 1" : "사용자 주석 1",
			"User Comment 2" : "사용자 주석 2",
			"User Comment 3" : "사용자 주석 3",
			"User Group" : "사용자 그룹",
			"User Group (1~10)" : "사용자 그룹 (1~10)",
			"User ID" : "사용자",
			"User ID 1" : "사용자 1",
			"User ID 2" : "사용자 2",
			"User ID 3" : "사용자 3",
			"User Menu Setup" : "사용자 메뉴 셋업",
			"User Name" : "사용자",
			"User Select Period" : "사용자 지정 기간",
			"User Setup" : "사용자 셋업",
			"User Time 1" : "사용자 시간 1",
			"User Time 2" : "사용자 시간 2",
			"User Time 3" : "사용자 시간 3",
			"Valid Table" : "유효 테이블",
			"Valid Table Type" : "유효 테이블 타입",
			"Validation Table" : "확인 테이블",
			"Value" : "값",
			"Value 1" : "값 1",
			"Value 2" : "값 2",
			"Value Count" : "값 개수",
			"Value Seq" : "Value Seq",
			"Value Table" : "값 테이블",
			"Value Type" : "값의 형태",
			"Variable Flag" : "데이터 가변 여부",
			"Variable Shift" : "불규칙 근무조",
			"Vendor" : "자재 공급자",
			"Vendor" : "툴 공급자",
			"Vendor Material" : "자재 제품",
			"Vendor Tool ID" : "공급자측 툴명",
			"Version" : "버전",
			"Version Setup" : "버전 셋업",
			"Vertical" : "세로",
			"Vertical Unit" : "세로 단위",
			"View 3 Sigma Line" : "3 시그마선 보기",
			"View Alarm History" : "알람 이력 조회",
			"View Character By Collection Set" : "콜랙션 셋별 캐릭터 조회",
			"View Character by Collection Set" : "콜랙션 셋별 캐릭터 조회",
			"View Character By Group" : "그룹별 캐릭터 조회",
			"View Chart" : "차트 조회",
			"View Chart List" : "차트 조회",
			"View Chart Options" : "차트 옵션 보기",
			"View Collection Set By Group" : "그룹별 콜랙션 셋 조회",
			"View Collection Set by MFO" : "MFO별 콜랙션 셋 조회",
			"View Control Chart" : "관리도 조회",
			"View Date" : "날짜 보기",
			"View EDC Data" : "EDC 데이터 조회",
			"View Event List by Event Group" : "그룹별 이벤트목록 조회",
			"View Excluded EDC History" : "제외된 EDC 이력 조회",
			"View Flow List By Operation" : "공정별 플로우목록 조회",
			"View Frequence Text" : "도수 보기",
			"View Grid Line" : "그리드 보기",
			"View Hold Lot List" : "보류 Lot 목록 조회",
			"View Inventory History" : "자재 이력 조회",
			"View Lot Alarm History" : "Lot 알람 이력 조회",
			"View Lot Assembly Status" : "Lot 조립 상태 조회",
			"View Lot BOM History" : "Lot BOM 이력 조회",
			"View Lot Data" : "Lot Data 조회",
			"View Lot Data by Collection Set" : "콜랙션 셋별 Lot Data 조회",
			"View Lot Data By Lot" : "Lot Data 조회",
			"View Lot History" : "Lot 이력 조회",
			"View Lot History Detail" : "Lot 이력 상세 조회",
			"View Lot List By Operation" : "공정별 Lot 목록 조회",
			"View Lot List by Operation" : "공정별 LOT 목록 상세 조회",
			"View Lot List by Resource" : "자원별 Lot 목록 조회",
			"View Lot List by Resource Group" : "자원 그룹별 Lot 목록 조회",
			"View Lot Recipe History" : "Lot 레서피 이력 조회",
			"View Lot Status" : "Lot 상태 조회",
			"View Lot Trace" : "Lot 이력 추적",
			"View Lot Trace Tree" : "Lot 이력 추적(트리형)",
			"View Material List By BOM Set ID" : "BOM Set ID별 제품목록 조회",
			"View Material List By Flow" : "플로우별 제품목록 조회",
			"View Material List By Group" : "그룹별 제품목록 조회",
			"View Multi Control Chart" : "다중 관리도 조회",
			"View Normal Line" : "정규 곡선 보기",
			"View OOC History" : "이상 발생 이력 조회",
			"View Planned Lot" : "계획 Lot 조회",
			"View PM Schedule - In view of Actor" : "PM 스케줄 조회 - PM 실시자용",
			"View PM Schedule - In view of Planner" : "PM 스케줄 조회 - PM 계획자용",
			"View Process Capability Report" : "공정능력 보고서 조회",
			"View Production Order" : "생산 지시 조회",
			"View Production Plan" : "생산 계획 조회",
			"View R-Chart" : "R 차트 보기",
			"View Resource Alarm History" : "장비 알람 이력 조회",
			"View Resource Data" : "자원 데이터 조회",
			"View Resource Data By Collection Set" : "콜랙션 셋별 자원 데이터 조회",
			"View Resource Down History" : "자원 이상 이력 조회",
			"View Resource History" : "자원 이력 조회",
			"View Resource History Detail" : "자원 이력 상세 조회",
			"View Resource Labor" : "생산 투입 인력 조회",
			"View Resource List by Group" : "그룹별 자원목록 조회",
			"View Resource List by Operation" : "공정별 자원목록 조회",
			"View Resource List Detail" : "자원 목록 상세 조회",
			"View Resource Status" : "자원 상태 조회",
			"View Return Lot List" : "반송 Lot 목록 조회",
			"View Rework Lot List" : "재작업 Lot 목록 조회",
			"View Rule Check" : "Rule 검사 보기",
			"View Shipped Lot List" : "출하 Lot 목록 조회",
			"View SPC Alarm History" : "SPC 알람 이력 조회",
			"View Spec History" : "스펙 이력 조회",
			"View Spec Limit" : "규격 한계 보기",
			"View Spec Limit Line" : "규격 한계선 보기",
			"View Sub Lot Recipe History" : "Sub Lot 레서피 이력 조회",
			"View Tool" : "툴 상태 조회",
			"View Tool Defect Data" : "툴 결함 조회",
			"View Tool History" : "툴 이력 조회",
			"View Tool List" : "툴 목록 조회",
			"View Tool List by Operation" : "공정별 툴 목록 조회",
			"View Tool List by Resource" : "자원별 툴 목록 조회",
			"View Trouble Lot List" : "이상 발생 Lot 목록 조회",
			"View Work Order" : "작업 지시 조회",
			"View XAxis Label" : "X축 라벨 보기",
			"Volume" : "부피",
			"Volume Unit" : "부피 단위",
			"Wait Receive Lot" : "수취 대기 Lot 목록",
			"Warn Message" : "경고 메세지",
			"Warn Queue Time" : "경고 Queue Time",
			"Warn User Group ID" : "경고 사용자 그룹",
			"Warning" : "경고",
			"Wed" : "수",
			"Wednesday" : "수요일",
			"Week" : "주",
			"Weight" : "중량",
			"Weight Gross" : "총중량",
			"Weight Net" : "순중량",
			"Weight Unit" : "중량 단위",
			"Width" : "폭",
			"Work Comment" : "생산 지시 주석",
			"Work Date" : "작업 날짜",
			"Work Hours" : "작업시간",
			"Work Hours of Day" : "요일별 작업시간",
			"Work Order Item" : "작업지시 항목",
			"Work Order Setup" : "작업 지시 셋업",
			"Work Order Type" : "생산 지시 타입",
			"Work Position" : "작업 위치",
			"Work Shift" : "작업조",
			"X Rule Type" : "X Rule 종류",
			"Xbarbar" : "Xbar 평균",
			"Year" : "년",
			"Year && Month" : "년/월",
			"Year /" : "년 /",
			"Year View" : "년 단위",
			"Zero Quantity Lot" : "0장 Lot만",
			"Attributes" : "속성들",
			"Attribute" : "속성",
			"Name" : "속성",
			"Current Value" : "현재 값",
			"Site ID" : "접속 사이트",
			"Connection" : "접속",
			"Network" : "네트웍",
			"Service" : "서비스",
			"Server Address" : "접속 서버주소",
			"Language" : "언어",
			"Sec" : "초",
			"Time Out" : "타임아웃",
			"Auto Logout Time" : "자동 로그아웃",
			"UI Option" : "화면 옵션",
			"Auto Refresh Time" : "자동 갱신시간",
			"No" : "아니오",
			"Yes" : "예",
			"Use Grid" : "그리드 사용",
			"Show Success Message" : "성공 메시지 표시",
			"List Refresh" : "리스트 갱신",
			"Bulletin Board" : "게시판"
		},
		Button : {
			"Acknowledge" : "수신 확인",
			"Add" : "추가",
			"App. Cancel" : "승인 취소",
			"Apply" : "적용",
			"Approval" : "승인",
			"Cancel" : "취소",
			"Change" : "변경",
			"Calculation" : "계산",
			"Clear" : "초기화",
			"Close" : "닫기",
			"Close All" : "모두 닫기",
			"Close Lot" : "반송 처리 Lot",
			"Continue" : "계속",
			"Control Chart" : "관리도",
			"Copy" : "복사",
			"Create" : "생성",
			"Data Change" : "데이터 변경",
			"Default Unit" : "기본 단위",
			"Delete" : "삭제",
			"Deselect All Rows" : "모든 줄 선택 해제",
			"End" : "Lot 작업 종료",
			"Exclude" : "제외",
			"Exit" : "닫기",
			"File Open" : "파일 열기",
			"Histogram" : "히스토그램",
			"Include" : "포함",
			"Monitoring" : "모니터링",
			"Move" : "Lot 이동",
			"No" : "아니오",
			"OK" : "확인",
			"Open" : "반송 처리",
			"Open Lot" : "반송 Lot",
			"Option" : "옵션",
			"Options" : "옵션",
			"Options..." : "옵션",
			"Pending" : "보류",
			"Print Test" : "시험 인쇄",
			"Process" : "실행",
			"Raw Data" : "데이터",
			"Redraw" : "Redraw",
			"Regenerate" : "재생성",
			"Release" : "배포",
			"Reset" : "리셋",
			"Return" : "반품",
			"Scrap" : "폐기",
			"Select" : "선택",
			"Select All Rows" : "모든 줄 선택",
			"Send" : "보내기",
			"Skip" : "Lot 스킵",
			"Start" : "Lot 작업 시작",
			"Stop" : "멈추기",
			"Trouble" : "이상 발생",
			"Trouble Lot" : "이상 Lot",
			"Trouble Resource" : "자원 이상 처리",
			"Undelete" : "삭제 취소",
			"Update" : "수정",
			"View" : "조회",
			"View Lot List" : "Lot 목록 조회",
			"View Order List" : "생산지시 목록 조회",
			"View Plan List" : "생산계획 목록 조회",
			"Yes" : "예",
			"Zoom" : "확대/축소",
			"Down" : "아래로",
			"Up" : "위로",
			"Remove" : "제거",
			"Detail" : "상세",
			"History" : "이력",
			"SQL Test" : "SQL 테스트"
		},
		Menu : {
			"[ALM]Alarm" : "[ALM]Alarm",
			"[BAS]Basic" : "[BAS]Basic",
			"[BOM]Bill Of Material" : "[BOM]Bill Of Material",
			"[EDC]Engineering Data Collection" : "[EDC]Engineering Data Collection",
			"[GCM]General Code Management" : "[GCM]General Code Management",
			"[INV]Inventory" : "[INV]Inventory",
			"[MSG]Message" : "[MSG]Message",
			"[POP]Label" : "[POP]Label",
			"[QCM]Quality Control Management" : "[QCM]Quality Control Management",
			"[RAS]Resource Allocation and Status" : "[RAS]Resource Allocation and Status",
			"[RCP]Recipe" : "[RCP]Recipe",
			"[RTD]Real Time Dispatcher" : "[RTD]Real Time Dispatcher",
			"[SEC]Security" : "[SEC]Security",
			"[SVM]Service Manager" : "[SVM]Service Manager",
			"[WFM]Work Flow Modeler" : "[WFM]Work Flow Modeler",
			"[WIP]Work In Process" : "[WIP]Work In Process",
			"[WIPX]Work In Process" : "[WIPX]Work In Process Extension",
			"About" : "About(설명)",
			"Adapt Lot" : "Adapt(Lot 특성 변경)",
			"Analysis" : "분석",
			"Analysis(&A)" : "분석(&A)",
			"Approval and Release BOM Set Version" : "BOM 승인 및 배포",
			"Approval and Release Collection Set Version" : "콜랙션 셋 승인 및 배포",
			"Approval and Release Inspection Set Version" : "검사 셋 승인 및 배포",
			"Approval and Release Recipe Version" : "레서피 승인 및 배포",
			"Assemble" : "Assemble(조립)",
			"Attach Character to Version" : "콜랙션 셋 버전에 캐릭터 등록",
			"Attach Chart to MFO" : "차트 MFO 셋업",
			"Attach Collection Set to MFO" : "콜랙션 셋 MFO 셋업",
			"Attach Inspection Item to Version" : "검사 아이템 버전에 등록",
			"Attach Lot To Order" : "생산 지시 - Lot 연결",
			"Attach Material to Version" : "BOM Set Version에 제품 등록",
			"Attach Recipe To MFO" : "레서피 MFO 셋업",
			"Attach User to Chart" : "차트 사용자 셋업",
			"Attribute" : "Attribute(Lot 속성 변경)",
			"Attribute Setup" : "속성 셋업",
			"BOM Set Setup" : "BOM Set 셋업",
			"Bonus Lot" : "Bonus(Lot 보상)",
			"Calendar Setup (Detail)" : "캘린더 상세 셋업",
			"Calendar Setup" : "캘린더 셋업",
			"Capability Analysis" : "공정능력 분석",
			"Carrier Setup" : "캐리어 셋업",
			"Change EDC Data" : "EDC 데이터 변경",
			"Change Lot Data" : "Lot Data 변경",
			"Change Password" : "암호 변경",
			"Change Port Status" : "포트 상태 변경",
			"Change Resource Data" : "자원 데이터 변경",
			"Character Setup" : "캐릭터 셋업",
			"Chart Set Setup" : "차트 셋 셋업",
			"Chart Setup" : "차트 셋업",
			"Clear Alarm" : "알람 초기화",
			"Client Upgrade" : "클라이언트 업그레이드",
			"Close All" : "모두 닫기",
			"Close All Windows" : "모든 창 닫기",
			"Close Return Lot" : "반송 Lot 처리",
			"Clean Lot Defect" : "Lot 결함 제거",
			"Collect Lot Defect" : "Lot 결함 수집",
			"Collect EDC Data by Chart Set" : "차트 셋 EDC 데이터 수집",
			"Collect Lot Data by Chart Set (Type 1)" : "차트 셋 Lot 데이터 수집 (Type 1)",
			"Collect Lot Data by Chart Set (Type 2)" : "차트 셋 Lot 데이터 수집 (Type 2)",
			"Collect Lot Data by Chart Set (Type 3)" : "차트 셋 Lot 데이터 수집 (Type 3)",
			"Collect Lot Data" : "Lot Data 수집",
			"Collect Resource Data by Chart Set (Type 1)" : "차트 셋 장비 데이터 수집 (Type 1)",
			"Collect Resource Data by Chart Set (Type 2)" : "차트 셋 장비 데이터 수집 (Type 2)",
			"Collect Resource Data by Chart Set (Type 3)" : "차트 셋 장비 데이터 수집 (Type 3)",
			"Collect Resource Data" : "자원 데이터 수집",
			"Collection Set Setup" : "콜랙션 셋 셋업",
			"Combine Extension" : "확장 결합",
			"Combine Lot" : "Combine(Lot 결합)",
			"Consume" : "자재 사용",
			"Control Chart" : "관리도 조회",
			"Convert Inventory To Lot" : "자재에서 Lot으로 변환",
			"Convert Lot To Inventory" : "Lot에서 자재로 변환",
			"Create Lot Based On Order" : "생산 지시에 의한 Lot 생성",
			"Create Lot Based On Plan" : "생산 계획에 의한 Lot 생성",
			"Create Planned Lot" : "계획된 Lot 생성",
			"Create Lot" : "Create(Lot 생성)",
			"Cycle Time Setup" : "작업 시간 셋업",
			"Delete BOM History" : "BOM 이력 삭제",
			"Delete Inventory History" : "자재 이력 삭제",
			"Delete Lot Data History" : "Lot 데이터 이력 삭제",
			"Delete Lot History" : "Lot 이력 삭제",
			"Delete Resource Data History" : "자원 데이터 이력 삭제",
			"Delete Resource History" : "자원 이력 삭제",
			"Delete Sublot History" : "Sublot 이력 삭제",
			"Delete Sub Resource History" : "서브 자원 이력 삭제",
			"Delete Tool History" : "툴 이력 삭제",
			"Disassemble" : "Disassemble(조립해제)",
			"Dispatcher Setup" : "디스페쳐 셋업",
			"Dispatcher" : "디스페쳐",
			"EDC Data Prompt Setup" : "EDC 데이터 문자열 셋업",
			"End Batch" : "Batch 종료",
			"End Lot" : "Lot 작업 종료",
			"End Sublot" : "Sublot 종료",
			"Event Setup" : "이벤트 셋업",
			"Event" : "Event(이벤트)",
			"Exit" : "프로그램 종료",
			"Factory Setup" : "공장 셋업",
			"Favorites Setup" : "즐겨찾기 셋업",
			"Favorites" : "즐겨찾기",
			"Flow Setup" : "플로우 셋업",
			"Function Group Setup" : "기능 그룹 셋업",
			"Function Setup" : "기능 셋업",
			"Future Action Setup" : "Future Action 셋업",
			"General Code Data Setup" : "General Code Data 셋업",
			"General Code Data Setup By Privilege" : "General Code Data 셋업(권한제한)",
			"General Code Table Setup" : "General Code Table 셋업",
			"Help" : "도움말",
			"Help(&H)" : "도움말(&H)",
			"Hold Lot" : "Hold(Lot 잠금)",
			"Image Setup" : "이미지 셋업",
			"In Inventory" : "자재 입고",
			"Inspection Item Setup" : "검사 아이템 셋업",
			"Inspection Material Setup" : "검사 제품 셋업",
			"Inspection Set Setup" : "검사 셋 셋업",
			"Inquiry" : "조회",
			"Inquiry(&I)" : "조회(&I)",
			"Label Design Setup" : "라벨 디자인 셋업",
			"Label Setup" : "라벨 셋업",
			"Label" : "라벨",
			"Local Repair Lot" : "Local Repair(Lot 공정내 수리)",
			"Log Out" : "로그아웃",
			"Loss Extension" : "확장 손실",
			"Loss Lot" : "Loss(Lot 손실)",
			"Alarm Setup" : "알람 셋업",
			"Lot ID Rule Setup" : "Lot ID 규칙 셋업",
			"Lot Label Print" : "Lot 라벨 인쇄",
			"Maintenance" : "유지보수",
			"Maintenance(&M)" : "유지보수(&M)",
			"Make Batch" : "Batch 생성",
			"Material Label Setup" : "제품 라벨 셋업",
			"Material Setup" : "제품 셋업",
			"Menu Window" : "메뉴 윈도우",
			"Menu" : "메뉴",
			"Merge Extension" : "확장 병합",
			"Merge Lot" : "Merge(Lot 병합)",
			"Message Setup" : "메시지 셋업",
			"Modify Lot Recipe" : "Lot 레서피 변경",
			"Modify Sublot Recipe" : "Sublot 레서피 변경",
			"Move Lot" : "Move(Lot 이동)",
			"Multi End Lot" : "Multi End(멀티 Lot 작업 종료)",
			"Multi Realtime Monitoring Control Chart" : "다중 실시간 관리도 모니터링",
			"Multi Start Lot" : "묶음 Lot 작업 시작",
			"Open Return Lot" : "반송 Lot 등록",
			"Operation Setup" : "공정 셋업",
			"Operation" : "공정",
			"Option" : "옵션",
			"Options" : "옵션",
			"Order" : "생산지시",
			"Out Inventory" : "자재 출고",
			"Partial Merge" : "Partial Merge(Lot 부분병합)",
			"Planned Lot Setup" : "계획 Lot 셋업",
			"PM Part Setup" : "PM 파트 셋업",
			"PM Schedule Setup" : "PM 스케줄 셋업",
			"PM Security Setup" : "PM 보안 셋업",
			"Port Setup" : "포트 셋업",
			"Privilege Definition Setup" : "특권 정의 셋업",
			"Privilege Group - User Relation Setup" : "권한 그룹 사용자 셋업",
			"Privilege Group Setup" : "권한 그룹 셋업",
			"Privilege Setup" : "권한 셋업",
			"Production Order Setup" : "생산 지시 셋업",
			"Production Plan Setup" : "생산 계획 셋업",
			"Queue Time Setup" : "Queue Time 셋업",
			"Raise Lot Alarm" : "Lot 알람 발생",
			"Raise Resource Alarm" : "장비 알람 발생",
			"Realtime Monitoring Control Chart" : "실시간 관리도 모니터링",
			"Receive Lot" : "Receive(Lot 수취)",
			"Recipe Setup" : "레서피 셋업",
			"Recipe Version Setup" : "레서피 버젼 셋업",
			"Release Lot" : "Release(Lot 잠금해제)",
			"Release Batch" : "Batch 배포",
			"Repair End Lot" : "Repair End(Lot 수리 종료)",
			"Repair Operation Setup" : "수리 공정 셋업",
			"Repair Lot" : "Repair(Lot 수리)",
			"Replace" : "Replace(교체)",
			"Replace Lot" : "Lot 대체변경",
			"Resource - Event Relation Setup" : "자원 이벤트 셋업",
			"Resource - Operation Relation Setup" : "자원 공정 셋업",
			"Resource Alarm Setup" : "장비 알람 셋업",
			"Resource Group Setup" : "자원 그룹 셋업",
			"Resource Labor Setup" : "생산 투입 인력 셋업",
			"Resource Setup" : "자원 셋업",
			"Resource" : "자원",
			"Rework Flow Setup" : "재작업 플로우 셋업",
			"Rework Lot" : "Rework(Lot 재작업)",
			"Rule Setup" : "디스페쳐 규칙 셋업",
			"Rework Sublot" : "Sublot 재작업",
			"Sampling Procedure Setup" : "샘플링 프로시저 셋업",
			"Scrap" : "자재 폐기",
			"Assign Function to Security Group" : "보안 그룹에 기능 셋업",
			"Security Group Setup" : "보안 그룹 셋업",
			"Send Message" : "메시지 보내기",
			"Setup" : "셋업",
			"Setup(&S)" : "셋업(&S)",
			"Ship Lot" : "Ship(Lot 출하)",
			"Skip Lot" : "Skip(Lot 스킵)",
			"Sort Extension" : "확장 정렬",
			"Spec Management" : "스펙 관리",
			"Split Extension" : "확장 분리",
			"Split Lot" : "Split(Lot 분리)",
			"Split-Merge Lot" : "Split-Merge(Lot 분리-병합)",
			"Start Batch" : "Batch 시작",
			"Start Lot" : "Lot 작업 시작",
			"Start Lot Extension" : "확장 Lot 작업 시작",
			"End Lot Extension" : "확장 Lot 작업 종료",
			"Store Lot" : "Store(Lot 스토어)",
			"Start Sublot" : "Sublot 시작",
			"Sublot Option Setup" : "Sublot 옵션 셋업",
			"Sub Resource Event" : "서브 자원 이벤트",
			"Sub Resource Setup" : "서브 자원 셋업",
			"System" : "시스템",
			"System(&Y)" : "시스템(&Y)",
			"Terminate Lot" : "Lot 폐기",
			"Tool - Event Relation Setup" : "툴 - 이벤트 셋업",
			"Tool Event Setup" : "툴 이벤트 셋업",
			"Tool Event" : "툴 이벤트",
			"Tool Setup" : "툴 셋업",
			"Tool Type Setup" : "툴 타입 셋업",
			"Top Menu - Setup" : "셋업",
			"Top Menu - Transaction" : "트랜잭션",
			"Top Menu - Analysis" : "분석",
			"Top Menu - Inquiry" : "조회",
			"Top Menu - Maintenance" : "유지보수",
			"Transaction" : "트랜잭션",
			"Transaction(&T)" : "트랜잭션(&T)",
			"Transfer Inventory" : "저장소 이동",
			"Trouble / Action Code Setup" : "이상발생 / 이상조치 코드 셋업",
			"Trouble Resource" : "자원 이상 처리",
			"Unstore Lot" : "Unstore(Lot 언스토어)",
			"Update Future Action" : "Future Action 변경",
			"Update Queue Time" : "Queue Time 변경",
			"User Menu Setup" : "사용자 메뉴 셋업",
			"User Setup" : "사용자 셋업",
			"Utilities" : "도구",
			"Utilities(&U)" : "도구(&U)",
			"View Alarm History" : "알람 이력 조회",
			"View Character By Collection Set" : "콜랙션 셋별 캐릭터 조회",
			"View Character By Group" : "그룹별 캐릭터 조회",
			"View Chart List" : "차트 조회",
			"View Collection Set By Group" : "그룹별 콜랙션 셋 조회",
			"View Collection Set by MFO" : "MFO별 콜랙션 셋 조회",
			"View EDC Data" : "EDC 데이터 조회",
			"View Event List by Event Group" : "그룹별 이벤트 목록 조회",
			"View Excluded EDC History" : "제외된 EDC 이력 조회",
			"View Flow List By Operation" : "공정별 플로우 목록 조회",
			"View Hold Lot List" : "보류 Lot 목록 조회",
			"View Inventory History" : "자재 이력 조회",
			"View Lot Alarm History" : "Lot 알람 이력 조회",
			"View Lot Assembly Status" : "Lot 조립 상태 조회",
			"View Lot BOM History" : "Lot BOM 이력 조회",
			"View Lot Data by Collection Set" : "콜랙션 셋별 Lot Data 조회",
			"View Lot Data" : "Lot Data 조회",
			"View Lot History Detail" : "Lot 이력 상세 조회",
			"View Lot History" : "Lot 이력 조회",
			"View Lot List By Operation" : "공정별 Lot 목록 조회",
			"View Lot List by Operation" : "공정별 Lot 목록 조회",
			"View Lot List by Resource Group" : "자원 그룹별 Lot 목록 조회",
			"View Lot List by Resource" : "자원별 Lot 목록 조회",
			"View Lot List Detail" : "LOT 목록 상세 조회",
			"View Lot Recipe History" : "Lot 레서피 이력 조회",
			"View Lot Status" : "Lot 상태 조회",
			"View Lot Trace" : "Lot 이력 추적",
			"View Lot Trace For Tree" : "Lot 이력 추적 트리",
			"View Material List By BOM Set ID" : "BOM Set ID별 제품 목록 조회",
			"View Material List By Flow" : "플로우별 제품 목록 조회",
			"View Material List By Group" : "그룹별 제품 목록 조회",
			"View OOC History" : "이상 발생 이력 조회",
			"View Planned Lot" : "계획 Lot 조회",
			"View PM Schedule - In view of Actor" : "PM 스케줄 조회 - PM 실시자용",
			"View PM Schedule - In view of Planner" : "PM 스케줄 조회 - PM 계획자용",
			"View Process Capability" : "공정능력 조회",
			"View Production Order" : "생산 지시 조회",
			"View Production Plan" : "생산 계획 조회",
			"View Resource Alarm History" : "장비 알람 이력 조회",
			"View Resource Data By Collection Set" : "콜랙션 셋별 자원 데이터 조회",
			"View Resource Data" : "자원 데이터 조회",
			"View Resource Down History" : "자원 이상 이력 조회",
			"View Resource History Detail" : "자원 이력 상세 조회",
			"View Resource History" : "자원 이력 조회",
			"View Resource Labor" : "생산 투입 인력 조회",
			"View Resource Status" : "자원 상태 조회",
			"View Return Lot List" : "반송 Lot 목록 조회",
			"View Rework Lot List" : "재작업 Lot 목록 조회",
			"View Shipped Lot List" : "출하 Lot 목록 조회",
			"View Alarm History" : "알람 이력 조회",
			"View Spec History" : "스펙 이력 조회",
			"View Sub Lot Recipe History" : "Sub Lot 레서피 이력 조회",
			"View Sub Resource History" : "서브 자원 이력 조회",
			"View Tool Defect Data" : "툴 결함 조회",
			"View Tool History" : "툴 이력 조회",
			"View Tool List by Operation" : "공정별 툴 목록 조회",
			"View Tool List by Resource" : "자원별 툴 목록 조회",
			"View Tool List" : "툴 목록 조회",
			"View Tool" : "툴 상태 조회",
			"View Trouble Lot List" : "이상 발생 Lot 목록 조회",
			"View Work Order" : "작업 지시 조회",
			"Window(&W)" : "윈도우(&W)",
			"Windows" : "윈도우",
			"Work Flow Modeler" : "작업 플로우 모델러",
			"Work Order Setup" : "작업 지시 셋업",
			"Modeler" : "모델러",
			"Bulletin Board" : "게시판",
			"Flexible Header Setup" : "목록 항목 설정",
			"Alarm Setup" : "알람 설정",
			"Attach Alarm to MFO/Resource" : "알람을 MFO 또는 설비에 설정",
			"Global Option Setup" : "글로벌 옵션 설정",
			"Sublot Option Setup" : "서브랏 옵션 설정",
			"MFO Option Setup" : "MFO 옵션 설정",
			"Yield Setup" : "수율 기준표 설정",
			"ID Generator Setup" : "ID 발번 규칙 설정",
			"ID Generator Relation Setup" : "ID 발번 규칙을 MFO 또는 설비에 설정",
			"Batch Creation Rule Setup" : "묶음 생성 규칙 설정",
			"Batch Creation Rule Relation Setup" : "묶음 생성 규칙을 설비에 설정",
			"Batch Keep Flag Setup" : "묶음 유지 설정",
			"Resource - Resource Group Relation Setup" : "설비 - 설비 그룹 관계 설정",
			"Resource MFO Relation Setup" : "설비를 MFO에 설정",
			"Carrier Group Setup" : "캐리어 그룹 설정",
			"Carrier Group Relation Setup" : "캐리어 그룹을 MFO 또는 설비에 설정",
			"Carrier Event Setup" : "캐리어 이벤트 설정",
			"Check Query Setup" : "체크 쿼리 설정",
			"Attach Query To Check List" : "체크 쿼리를 체크 리스트에 설정",
			"Check Type Definition" : "체크 타입 정의",
			"Attach Material Setup" : "자재를 BOM 셋에 설정",
			"Approval and Release Setup" : "승인 및 배포 설정",
			"Attach Character" : "캐릭터를 콜랙션셋에 설정",
			"Approval Release Setup" : "승인 및 배포 설정",
			"Attach Recipe To MFO Setup" : "레시피를 MFO에 설정",
			"Dispatcher Rule Setup" : "디스패치 규칙 설정",
			"Dispatcher Relation Setup" : "디스패치 적용공정 설정",
			"Dispatcher Simulation Setup" : "디스패치 시뮬레이션 설정",
			"Dispatcher Rule Item Setup" : "디스패치 규칙 항목 설정",
			"Reference Operation Setup" : "디스패치 참조 공정 설정",
			"Dispatch Event Configuration Setup" : "디스패치 트리거 설정",
			"Attach Inspection Item To Version Setup" : "검사 항목을 버전에 설정",
			"Approval and Release Inspection Set Version Setup" : "승인 및 배포 설정",
			"Member Setup" : "멤버 설정",
			"Service Member Setup" : "서비스 생성 및 서비스 멤버 설정",
			"Active Service Version Setup" : "활성 서비스 버전 설정",
			"Service User Routine Setup" : "서비스 Customizing 설정",
			"Count Variance" : "수량 변경",
			"Multi Terminate Lot" : "복수 Lot 폐기",
			"Reserve Lot" : "Lot 예약",
			"Unreserve Lot" : "Lot 예약 해제",
			"Make SubLot Batch" : "서브랏 묶음 생성",
			"Reserve Lot Batch" : "묶음 Lot 예약",
			"Reserve Sub Lot Batch" : "묶음 서브랏 예약",
			"Delete Start Batch" : "묶음 시작 취소",
			"Scribe Extension" : "확장 면취",
			"Change CMF Value" : "Lot의 CMF 값 변경",
			"Tran Event" : "설비 이벤트",
			"Resource Event" : "설비 이벤트",
			"Delete Resource History" : "설비 이력 삭제",
			"Sub Resource Event" : "서브 설비 이벤트",
			"Carrier Event" : "캐리어 이벤트",
			"Clean Carrier" : "캐리어 청소",
			"Attach Lot To Carrier" : "Lot을 캐리어에 할당",
			"Attach Carrier To Lot" : "캐리어를 Lot에 할당",
			"Assign SublotTo Carrier" : "서브랏을 캐리어에 할당",
			"Carrier Change" : "캐리어 변경 및 교환",
			"Tool Event" : "툴 이벤트",
			"Delete Tool History" : "툴 이력 삭제",
			"Make Check Result" : "체크 결과 작성",
			"Change Port State" : "포트 상태 변경",
			"Change Transfer State" : "포트 운송 상태 변경",
			"Change Association State" : "포트 할당 상태 변경",
			"Change Access Mode State" : "포트 사용 상태 변경",
			"Change Reservation State" : "포트 예약 상태 변경",
			"Delete EDC Data History" : "EDC 수집 데이터 이력 삭제",
			"Assembly Lot" : "Lot 조립",
			"Disassemble Lot" : "Lot 해체",
			"Tran In Store" : "창고 입고",
			"Tran Out Store" : "창고 불출",
			"Tran Transfer Store" : "창고간 이동",
			"Tran Convert Inventory Type To Lot" : "자재를 Lot으로 변경",
			"Tran Convert Lot To Inventory Type" : "Lot을 자재로 변경",
			"Tran Consume" : "자재 소비",
			"Tran Scrap" : "자재 불량",
			"Tran Delete Inventory History" : "자재 이력 삭제",
			"Modify Lot Recipe" : "Lot 레시피 변경",
			"Modify Sublot Recipe" : "서브랏 레시피 변경",
			"Adjust Lot Priority" : "Lot 우선순위 변경",
			"Re-Dispatch Lot" : "Lot에 대해 다시 디스패치",
			"Tran Lot Label Print" : "Lot 라벨 인쇄",
			"Create QCM Batch" : "QCM 묶음 생성",
			"Result Recording" : "확인 결과 저장",
			"Final Decision" : "최종 판정",
			"Request Reinspection" : "재 판정 요청",
			"Raise Alarm" : "알람 발생",
			"Input Attribute Value" : "속성 데이터 입력",
			"Input Attribute Value by Privilege" : "속성 데이터 입력(권한제한)",
			"View Sheet History" : "장표 재발행",
			"View LotList By Product" : "제품별 Lot 목록 조회",
			"View Laser Marking Lot" : "Laser Marking Lot 조회",
			"Ingot Lot 공정별 실적조회" : "Ingot Lot 공정별 실적조회",
			"공정별 실적집계 현황(Lot별)" : "공정별 실적집계 현황(Lot별)",
			"공정별 실적집계 현황(품목별)" : "공정별 실적집계 현황(품목별)",
			"View Data List By Attribute" : "Lot 속성별 데이터 조회",
			"View Material By Group" : "제품 그룹에 의한 목록 조회",
			"View Material By Flow" : "플로우별 제품 조회",
			"View Flow By Operation" : "공정별 플로우 조회",
			"View Transit Lot List" : "이송 Lot 목록 조회",
			"View Lot Bonus List" : "Lot의 보너스 목록 조회",
			"View Lot Loss List" : "Lot의 불량 목록 조회",
			"View Lot Defect List" : "Lot의 결함 목록 조회",
			"View Batch Status" : "묶음 상태 조회",
			"View Batch History" : "묶음 이력 조회",
			"View Sublot Status" : "서브랏 상태 조회",
			"View Sublot List" : "서브랏 목록 조회",
			"View Sublot History" : "서브랏 이력 조회",
			"View Sublot Loss List" : "서브랏 불량 목록 조회",
			"View Resource By Group" : "설비그룹에 의한 목록 조회",
			"View Resource By MFO" : "공정 설비 목록 조회",
			"View Lot By Resource" : "설비에서 작업중인 Lot 목록 조회",
			"View Event By Group" : "이벤트 그룹에 의한 목록 조회",
			"View Carrier Status" : "캐리어 상태 조회",
			"View Carrier History" : "캐리어 이력 조회",
			"View Carrier History By Lot" : "Lot에 의한 캐리어 이력 조회",
			"View Carrier Lot List" : "캐리어 Lot 목록 조회",
			"View Carrier Slot History" : "캐리어 슬롯 변경 이력 조회",
			"View Port History" : "포트 이력 조회",
			"View Check Result" : "체크 결과 조회",
			"View Lot Status For Assembly" : "조립 상태 조회",
			"View Lot History For Assembly" : "조립 이력 조회",
			"View Sublot Recipe History" : "서브랏 레시피 이력 조회",
			"View Attribute Status" : "속성 상태 조회",
			"View Attribute History" : "속성 이력 조회",
			"View Dispatch Event Interface History" : "디스패치 트리거 이력 조회",
			"View Pre-Dispatched History" : "선행 디스패치 이력 조회",
			"View Dispatched Lot List" : "디스패치된 Lot 목록 조회",
			"View Dispatched Resource List" : "디스패치된 설비 목록 조회",
			"View QC Batch Status" : "QC 묶음 상태 조회",
			"View QC Batch History" : "QC 묶음 이력 조회",
			"View Inspection History" : "판정 이력 조회",
			"View QC Batch List" : "QC 묶음 목록 조회",
			"View Service Member" : "서비스 멤버 목록 조회",
			"View Service Performance" : "서비스 성능 조회",
			"View Service Error" : "서비스 에러 조회",
			"Split to Carrier Lot" : "캐리어/블락 Lot으로 분리",
			"Attach Shipping List" : "출하 Lot 목록 구성",
			"INGOT 수입검사 성적서" : "INGOT 수입검사 성적서",
			"View Ingotlot Production List" : "Ingot Lot 생성 목록 조회",
			"View Reserved Block List" : "예약 Block 목록 조회",
			"Spec Management Setup" : "차트 스펙 설정",
			"Attach User to Chart Setup" : "차트 사용자 설정",
			"Trouble and Action Code Setup" : "이상발생 / 이상조치 코드 설정",
			"EDC Prompt Setup" : "EDC 문자열 설정",
			"Collect Lot Data" : "Lot Data 수집",
			"Collect Resource Data" : "설비 Data 수집",
			"Clear Alarm" : "알람 초기화",
			"Collect EDC Data by Chart Set" : "차트 셋으로 Lot Data 수집",
			"Tran Collect Resource Data by Chart Set (Type1)" : "차트 셋으로 설비 Data 수집 (타입1)",
			"Tran Collect Lot Data by Chart Set (Type2)" : "차트 셋으로 Lot Data 수집 (타입2)",
			"Tran Collect Resource Data by Chart Set (Type2)" : "차트 셋으로 설비 Data 수집 (타입2)",
			"Tran Collect Lot Data by Chart Set (Type3)" : "차트 셋으로 Lot Data 수집 (타입3)",
			"Tran Collect Resource Data by Chart Set (Type3)" : "차트 셋으로 설비 Data 수집 (타입3)",
			"Analysis Realtime Monitoring Control Chart" : "실시간 관리도 분석",
			"Analysis Multi Realtime Monitoring Control Chart" : "실시간 다중 관리도 분석",
			"Analysis Control Chart" : "관리도 분석",
			"View Control Chart" : "관리도 분석",
			"Analysis Capability Analysis" : "공정 능력 분석",
			"Inquiry View EDC Data" : "EDC Data 조회",
			"Inquiry View OOC History" : "이상발생 이력 조회",
			"Inquiry View Process Capability" : "공정 능력 조회",
			"View Alarm History" : "알람 이력 조회",
			"View Lot List by Operation" : "공정의 Lot 목록 조회",
			"Inquiry View Resource List Detail" : "설비 목록 조회",
			"Inquiry View Excluded EDC History" : "제외된 수집 Data 이력 조회",
			"Inquiry View Chart List" : "차트 목록 조회",
			"Maintenance Lot Data" : "Lot Data 관리",
			"Setup Privilege" : "권한 설정",
			"Resource MFO Relationship Setup" : "설비를 MFO에 설정",
			"Setup Active Service Version" : "활성 서비스 버전 설정",
			"Flexible Screen Setup" : "화면 디자인 셋업",
			"Flexible Screen Relation Setup" : "화면 디자인을 MFO/장비에 설정",
			"Flexible Inquiry Setup" : "조회 화면 설정",
			"Flexible Inquiry" : "Flexible Inquiry",
			"Step Setup" : "스텝 셋업",
			"Step MFO Relation Setup" : "스텝을 MFO에 설정",
			"Delete Lot History For Step" : "Lot의 스텝 이력 삭제",
			"View Lot History For Step" : "Lot의 스텝 이력 조회",
			"Group Definition Setup" : "그룹 설정",
			"Customized Field Setup" : "사용자 정의 설정",
			"Input Operation Value Setup" : "공정별 정보 입력 설정",
			"Regenerate Lot" : "Lot 재활성",
			"Start Lot For Step" : "스텝 시작",
			"End Lot For Step" : "스텝 종료"
		}
	},
	Message : {
		"0" : "옵션을 로딩 중입니다...",
		"1" : "리소스를 로딩 중입니다...",
		"2" : "메시지 버스를 로딩 중입니다...",
		"3" : "이 옵션을 적용하기 위해서는 프로그램을 새로 시작하여야 합니다. 새로 시작하시겠습니까?",
		"4" : "프로그램을 종료하시겠습니까?",
		"5" : "프로그램을 다시 시작하시겠습니까?",
		"6" : "이 버전은 현재 서버와 맞지 않습니다. 최신 버전을 받겠습니다.",
		"7" : "Auto logout 시간이 초과되었습니다. 프로그램이 자동 종료됩니다.",
		"8" : "Language XML File을 읽는 동안 에러가 발생했습니다.",
		"9" : "이 버전은 현재 서버와 맞지 않습니다. 최신 버전을 받으시겠습니까?.",
		"10" : "계속 하시겠습니까?.",
		"11" : "최신 버전을 받으시겠습니까?.",
		"12" : "알람 메세지가 도착했습니다!!!",
		"13" : "로그오프 하시겠습니까?",
		"51" : "CMN051 INFO - 응답을 기다리고 있습니다 ...",
		"52" : "CMN052 INFO - 작업을 성공적으로 수행하였습니다.",
		"53" : "CMN053 INFO - 데이타를 지우시겠습니까?",
		"54" : "CMN054 INFO - 이 명령을 수행하면 이와 관련된 여러 데이타가 데이타베이스에서 삭제됩니다. 그래도 지우시겠습니까?",
		"55" : "CMN055 INFO - 새로운 즐겨찾기를 적용하기 위해서는 다시 시작해야 합니다.",
		"56" : "CMN056 INFO - PM 계획이 정상적으로 수립되었습니다. 그런 이미 정의되었거나 PM이 수행되어 SCHEDULE에서 제외된 날이 있으니 이런 날에 대해서는 비주기적으로 SCHEDULE하여 주십시요. ",
		"57" : "CMN057 INFO - 이미 정의되었거나 PM이 수행되어 SCHEDULE이 불가능한 날이 있습니다. 이를 제외하고 Schedule을 계속 진행하시겠습니까?",
		"58" : "CMN058 INFO - 이 Lot은 Queue Time 설정시간이 지났습니다. 알람을 무시하고 계속 진행하시겠습니까?",
		"59" : "CMN059 INFO - 이 명령을 수행하면 차트의 이와 관련된 여러 데이타가 업데이트됩니다. 그래도 계속하시겠습니까?",
		"60" : "CMN060 INFO - 할당할 수 있는 최대 GDI 리소스를 초과하여 새로운 화면을 열수 없습니다. 사용하지 않는 화면을 닫아주십시오.",
		"61" : "CMN061 INFO - Excel 변환 중 에러가 발생 하였습니다. Excel에서 지원할 수 없는 칼럼수를 변환 하였는지 확인해 주십시오.",
		"101" : "CMN101 ERROR - 서버에서 응답이 없습니다!",
		"102" : "CMN102 ERROR - 알수 없는 오류가 발생했습니다.",
		"103" : "CMN103 ERROR - 메세지 에러가 발생했습니다. ",
		"104" : "CMN104 ERROR - 메시지 버스를 초기화에 실패 하였습니다. 메시지 버스가 제대로 설치 되었는지 확인하십시요!",
		"105" : "CMN105 ERROR - 귀하는 등록된 사용자이나 MES의 function을 사용할수 있는 권한이 없습니다.",
		"106" : "CMN106 ERROR - Function을 사용할 권한이 없습니다.",
		"107" : "CMN107 ERROR - 데이타가 입력되지 않았습니다. 필요한 데이타를 입력해 주십시요.",
		"108" : "CMN108 ERROR - 이 필드는 입력이 필요한 필드입니다. 데이타를 입력해 주십시요.",
		"109" : "CMN109 ERROR - Item이 선택되지 않았습니다. Item을 선택해 주십시요.",
		"110" : "CMN110 ERROR - DATA 형식이 올바르지 않습니다. 다시 입력해 주세요.",
		"111" : "CMN111 ERROR - 데이타가 다른 데이타와 중복됩니다.",
		"112" : "CMN112 ERROR - 이 Lot은 Start 시킬수 있는 상태가 아닙니다.",
		"113" : "CMN113 ERROR - 이 LOT의 M-F-O(Material-Flow-Operation) 정보가 올바르지 않습니다.",
		"114" : "CMN114 ERROR - 0보다 큰 값을 입력해 주세요.",
		"115" : "CMN115 ERROR - Operation은 최소 1개의 Unit을 가지고 있어야 합니다.",
		"116" : "CMN116 ERROR - 이 필드는 숫자를 입력해야 하는 필드입니다.",
		"117" : "CMN117 ERROR - 같은 Material로 복사할 수 없습니다.",
		"118" : "CMN118 ERROR - 리소스의 History가 없습니다.",
		"119" : "CMN119 ERROR - Lot의 History가 없습니다.",
		"120" : "CMN120 ERROR - 시작 날짜가 부적절 합니다.",
		"121" : "CMN121 ERROR - 리소스를 선택해 주세요.",
		"122" : "CMN122 ERROR - 리소스가 존재하지 않습니다.",
		"123" : "CMN123 ERROR - 입력된 Password가 다릅니다. 다시 입력하여 주세요.",
		"124" : "CMN124 ERROR - 등록되지 않은 User Group입니다. 먼저 User group을 등록해 주세요.",
		"125" : "CMN125 ERROR - 입력수량이 현재의 수량을 초과해서는 안됩니다.",
		"126" : "CMN126 ERROR - 입력한 값이 한계값을 넘었습니다. 다른 수를 입력해 주세요.",
		"127" : "CMN127 ERROR - 리소스를 로딩하는 도중 문제가 발생하였습니다. 리소스 화일이 존재하는지 확인하십시요!",
		"128" : "CMN128 ERROR - UPGRADE PROGRAM을 찾을 수 없습니다. CLIENT를 다시 SETUP 하세요.",
		"129" : "CMN129 ERROR - Step이 올바르지 않습니다. Step을 확인하세요.",
		"130" : "CMN130 ERROR - Key값의 Size는 0과 같거나 크고 30과 같거나 작아야 합니다.",
		"131" : "CMN131 ERROR - Data값의 Size는 0과 같거나 크고 50과 같거나 작아야 합니다.",
		"132" : "CMN132 ERROR - 이 Character는 이미 존재 합니다.",
		"133" : "CMN133 ERROR - 최소한 1개 이상의 아이템을 선택해 주세요.",
		"134" : "CMN134 ERROR - 선택된 아이템의 개수가 최대 개수를 초과했습니다.",
		"135" : "CMN135 ERROR - SPLIT 수량이 현재의 수량을 초과해서는 안됩니다.",
		"136" : "CMN136 ERROR - MERGE 수량이 현재의 수량을 초과해서는 안됩니다.",
		"137" : "CMN137 ERROR - COMBINE 수량이 현재의 수량을 초과해서는 안됩니다.",
		"138" : "CMN138 ERROR - Field Mask 값은 'Y', 'N', Space 문자만을 허용합니다.",
		"139" : "CMN139 ERROR - 실수형의 값만 허용됩니다. 값을 수정해 주세요.",
		"140" : "CMN140 ERROR - 정수형의 값만 허용됩니다. 값을 수정해 주세요.",
		"141" : "CMN141 ERROR - Unit Count의 값은 1 부터 MAX 까지입니다. 값을 수정해 주세요.",
		"142" : "CMN142 ERROR - Value Count의 값은 1 부터 MAX 까지입니다. 값을 수정해 주세요.",
		"143" : "CMN143 ERROR - USL 은 UCL의 값보다 커야합니다. UCL 을 확인해 주세요.",
		"144" : "CMN144 ERROR - LCL 은 LSL의 값보다 커야합니다. USL 을 확인해 주세요.",
		"145" : "CMN145 ERROR - USL 은 LSL의 값보다 커야합니다. LSL 을 확인해 주세요.",
		"146" : "CMN146 ERROR - UCL 은 LCL의 값보다 커야합니다. LCL 을 확인해 주세요.",
		"147" : "CMN147 ERROR - RUSL 은 RUCL의 값보다 커야합니다. RUCL 을 확인해 주세요.",
		"148" : "CMN148 ERROR - RLCL 은 RLSL의 값보다 커야합니다. RUSL 을 확인해 주세요.",
		"149" : "CMN149 ERROR - RUSL 은 LSL의 값보다 커야합니다. RLSL 을 확인해 주세요.",
		"150" : "CMN150 ERROR - RUCL 은 RLCL의 값보다 커야합니다. RLCL 을 확인해 주세요.",
		"151" : "CMN151 ERROR - 최소한 1개 이상의 Character를 선택해 주세요.",
		"152" : "CMN152 ERROR - Version을 선택해 주세요.",
		"153" : "CMN153 ERROR - 데이타의 길이가 최대 길이를 초과했습니다. 데이타 길이를 수정해 주세요.",
		"154" : "CMN154 ERROR - 데이타가 없습니다. LOT 정보를 확인해주십시오.",
		"155" : "CMN155 ERROR - 데이터를 차례대로 입력해주세요.",
		"156" : "CMN156 CONFIRM - 삭제된 장비입니다. 복구 하시겠습니까? ",
		"157" : "CMN157 ERROR - Collection Set 정보가 올바르지 않습니다.",
		"158" : "CMN158 ERROR - Collection Set Version 정보가 올바르지 않습니다.",
		"159" : "CMN159 ERROR - 이 Unit는 이미 존재 합니다.",
		"160" : "CMN160 ERROR - To Tran Time 은 From Tran Time의 값보다 커야합니다. To Tran Time 을 확인해 주세요.",
		"161" : "CMN161 ERROR - Resource History를 선택해 주세요.",
		"162" : "CMN162 CONFIRM - Mother Lot의 Material과 Child Lot의 Material이 일치 하지 않습니다. 계속하시겠습니까?",
		"163" : "CMN163 CONFIRM - Mother Lot의 Operation과 Child Lot의 Operation이 일치 하지 않습니다. 계속하시겠습니까?",
		"164" : "CMN164 ERROR - 이 Lot은 이미 존재 합니다. Lot을 확인 하세요.",
		"165" : "CMN165 ERROR - 최소한 1개 이상의 Material를 선택해 주세요.",
		"166" : "CMN166 ERROR - 이 Material는 이미 존재 합니다.",
		"167" : "CMN167 ERROR - LOT의 BOM_SET_VERSION 이 최신 BOM_SET_VERSION과 일치하지 않습니다. 기존 BOM_SET_VERSION 으로 계속 진행하시겠습니까?",
		"168" : "CMN168 ERROR - WORK SHIFT 형식이 올바르지 않습니다. ' '이나 1~4 중 선택해주세요.",
		"169" : "CMN169 ERROR - OUT 수량이 현재의 수량을 초과해서는 안됩니다.",
		"170" : "CMN170 ERROR - Transfer 하려는 Inventory가 같습니다. 다른 Inventory를 선택하세요.",
		"171" : "CMN171 ERROR - CONVERT 수량이 현재의 수량을 초과해서는 안됩니다.",
		"172" : "CMN172 ERROR - Order In 수량이 Order 수량을 초과해서는 안됩니다.",
		"173" : "CMN173 ERROR - 선택한 Order는 이미 삭제 되었습니다.",
		"174" : "CMN174 ERROR - 현재 SHIFT와 이전 SHIFT와의 관계가 부적합합니다.",
		"175" : "CMN175 ERROR - DISPLAY_PRECISION 는 10 보다 작아야 합니다.",
		"176" : "CMN176 ERROR - 최소 1개의 장비와 PM 날짜를 선택하셔야 합니다.",
		"177" : "CMN177 ERROR - 계획 날짜는 항상 현재이거나 미래이어야 합니다.",
		"178" : "CMN178 ERROR - PM 계획 날짜가 부적절 합니다.",
		"179" : "CMN179 ERROR - 선택하신 PM 주기에서는 주기적으로 PM을 실시할 수 없습니다. 다른 PM주기를 선택해 주세요.",
		"180" : "CMN180 ERROR - PM을 이미 수행했으므로 스케줄을 삭제또는 변경할 수 없습니다.",
		"181" : "CMN181 ERROR - 선택하신 날짜에는 계획된 PM Schedule이 없습니다.",
		"182" : "CMN182 ERROR - 선택하신 날짜에는 계획된 PM Schedule이 이미 있습니다.",
		"183" : "CMN183 ERROR - Rework Flow, Operation이 현재 Flow, Operation과 같습니다.",
		"184" : "CMN184 ERROR - Operation을 선택하세요.",
		"185" : "CMN185 ERROR - SHIFT 형식이 올바르지 않습니다. 'P', 'T', 'N' 중에서 선택해주세요.",
		"186" : "CMN186 ERROR - From Flow, Operation이 현재 Flow, Operation과 같습니다.",
		"187" : "CMN187 ERROR - Lot id 가 올바르지 않습니다. Lot id를 체크해 주세요.",
		"188" : "CMN188 ERROR - 선택한 아이템의 개수가 빈 Slot수를 초과했습니다.",
		"189" : "CMN189 ERROR - 데이타가 최대값을 초과했습니다.",
		"190" : "CMN190 CONFIRM - Lot의 Quantity가 0입니다. 계속 하시겠습니까?",
		"191" : "CMN191 CONFIRM - 전량 Split 하시겠습니까?",
		"192" : "CMN192 ERROR - 삭제할 이력이 없습니다. 이력을 다시 조회하세요.",
		"193" : "CMN193 CONFIRM - 카셋트에 여유공간이 부족합니다. 계속 하시겠습니까?",
		"194" : "CMN194 ERROR - Class Type이 다르면 같은 레벨에 설정할 수 없습니다. 레벨을 바꿔주십시오.",
		"195" : "CMN195 ERROR - 이 공정에는 Rework Code Table이 설정되어 있지 않습니다. 먼저 Rework Code Table를 설정하세요.",
		"196" : "CMN196 ERROR - 이미 Cleared된 알람입니다.",
		"197" : "CMN197 ERROR - 하나의 TOOL EVENT에서 Defect Data 수집과 제거를 동시에 진행할 수 없습니다.",
		"198" : "CMN198 ERROR - LOSS 수량이 현재의 수량을 초과해서는 안됩니다.",
		"199" : "CMN199 ERROR - 선택된 Lot이 없습니다. 먼저 Lot을 선택하여 주세요.",
		"200" : "CMN200 ERROR - Batch 수량이 Batch의 최대 수량을 초과해서는 안됩니다.",
		"201" : "CMN201 ERROR - Batch 수량이 Inspection Set의 최대 수량을 초과해서는 안됩니다.",
		"202" : "CMN202 ERROR - 입력수량이 현재의 수량과 일치하지 않습니다..",
		"203" : "CMN203 ERROR - Equipment Type에 대한 권한이 없습니다.",
		"204" : "CMN204 ERROR - 이 RECIPE VERSION은 이미 승인되었습니다.",
		"205" : "CMN205 ERROR - 이 PARAMETER는 이미 존재합니다.",
		"206" : "CMN206 ERROR - UCL은 CL의 값보다 커야합니다. CL을 확인해 주세요.",
		"207" : "CMN207 ERROR - CL은 LCL의 값보다 커야합니다. LCL을 확인해 주세요.",
		"208" : "CMN208 CONFIRM - 삭제된 차트입니다. 복구 하시겠습니까? ",
		"209" : "CMN209 ERROR - UCL2은 CL2의 값보다 커야합니다. CL2을 확인해 주세요.",
		"210" : "CMN210 ERROR - CL2은 LCL2의 값보다 커야합니다. LCL2을 확인해 주세요.",
		"211" : "CMN211 CONFIRM - OOC 이력에 대한 정보를 아직 다 입력하지 않았습니다. 창을 닫으시겠습니까?",
		"212" : "CMN212 ERROR - 적용 시작 시간은 현재 시간 보다 커야 합니다.",
		"213" : "CMN213 ERROR - 적용 시작 시간은 적용 완료 시간 보다 커야 합니다.",
		"214" : "CMN214 ERROR - To Time은 From Time 보다 커야 합니다.",
		"215" : "CMN215 ERROR - 데이터를 변경하시겠습니까?",
		"216" : "메세지가 도착하였습니다.",
		"217" : "CMN217 ERROR - 데이터가 올바르지 않습니다.",
		"218" : "CMN218 ERROR - USL은 TARGET의 값보다 커야합니다. TARGET을 확인해 주세요.",
		"219" : "CMN219 ERROR - TARGET은 LSL의 값보다 커야합니다. LSL을 확인해 주세요.",
		"220" : "CMN220 ERROR - Chart ID 가 중복됩니다.",
		"221" : "CMN221 ERROR - 데이터를 분석에서 제외하시겠습니까?",
		"222" : "CMN222 ERROR - 데이터를 분석에 포함하시겠습니까?",
		"223" : "CMN223 ERROR - Unit Count가 1보다 작기 때문에 이 캐릭터는 SPC와 연동시킬 수 없습니다.",
		"224" : "CMN224 ERROR - Sample Size가 1보다 작기 때문에 이 캐릭터는 SPC와 연동시킬 수 없습니다.",
		"225" : "CMN225 ERROR - 'Spec Out Unit Flag'값과 'Use Unit Flag' 값이 다르기 때문에 이 캐릭터는 SPC와 연동시킬 수 없습니다.",
		"226" : "CMN226 ERROR - 'Blank Save Flag'값이 'Y'이기 때문에 이 캐릭터는 SPC와 연동시킬 수 없습니다.",
		"227" : "CMN227 ERROR - Sample Size가 2보다 작기 때문에 이 캐릭터는 SPC와 연동시킬 수 없습니다.",
		"228" : "CMN228 ERROR - 레이아웃 밖으로 콘트롤이 존재합니다. 강제로 이동하시겠습니까?",
		"229" : "CMN229 ERROR - UDR 그룹 밖으로 콘트롤이 존재합니다. 강제로 이동하시겠습니까?",
		"230" : "CMN230 ERROR - 변경된 디자인을 저장하시겠습니까?",
		"231" : "CMN231 ERROR - 변경된 디자인을 새로 로딩하시겠습니까?",
		"232" : "CMN232 ERROR - 장비의 X 좌표가 레이아웃 영역을 벗어났습니다. 레이아웃 안으로 이동하시겠습니까?",
		"233" : "CMN233 ERROR - 장비의 Y 좌표가 레이아웃 영역을 벗어났습니다. 레이아웃 안으로 이동하시겠습니까?",
		"234" : "보다 큰 값을 입력해 주십시요.",
		"235" : "보다 작은 값을 입력해 주십시요.",
		"236" : "보다 작거나 같은 값을 입력해 주십시요.",
		"237" : "CMN237 ERROR - SUBLOT GRADE에 대한 LOSS CODE를 입력해 주십시오.",
		"238" : "CMN238 ERROR - CELL GRADE는 모든 CELL의 값을 가지고 있어야 합니다.",
		"239" : "CMN239 ERROR - UNIT2의 LOSS CODE 수량과 QTY_2의 SCRAP 수량이 일치하지 않습니다.",
		"240" : "CMN240 ERROR - LOSS CODE에 대한 SUBLOT GRADE를 입력해 주십시오.",
		"241" : "CMN241 ERROR - 이 캐릭터는 SPC와 연동되어 있기 때문에 데이터를 모두 입력하거나 모두 공백이여야 합니다. 확인해주세요.",
		"242" : "CMN242 ERROR - 이 CHART SET은 차트가 등록되어 있지 않습니다. 다른 CHART SET을 선택해주세요. ",
		"243" : "CMN243 ERROR - 이 캐리어에 담긴 LOT의 수량을 초과하여 SUBLOT을 할당할 수 없습니다. ",
		"244" : "CMN244 ERROR - 지정한 기간동안에는 데이터가 없습니다.",
		"245" : "CMN245 CONFIRM - Data가 더 있습니다. 계속 하시겠습니까?",
		"246" : "CMN246 ERROR - Column Count가 256를 초과 하여 Excel로 Download할 수 없습니다.",
		"247" : "CMN247 ERROR - 이 공정에는 Loss Code Table 이 존재하지 않습니다. 공정설정을 확인하십시오.",
		"248" : "CMN248 ERROR - 이 공정에는 Bonus Code Table 이 존재하지 않습니다. 공정설정을 확인하십시오.",
		"249" : "CMN249 ERROR - Rework Code가 선택되지 않았습니다.",
		"250" : "CMN250 ERROR - 변경된 데이터가 존재합니다. 데이터를 저장하시겠습니까?",
		"251" : "CMN251 ERROR - 소스 캐리어와 대상 캐리어가 동일합니다. 다른 캐리어를 선택하십시오.",
		"252" : "CMN252 ERROR - 이 화면에서는 Sublot을 가진 Lot의 Carrier 할당을 지원하지 않습니다. [Assign Sublot to Carrier] 화면을 사용하십시오.",
		"253" : "CMN253 ERROR - 이 화면에서는 Sublot이 없는 Lot의 Carrier 할당을 지원하지 않습니다. [Attach Carrier to Lot] 화면을 사용하십시오.",
		"254" : "CMN254 ERROR - 이 Lot은 Carrier를 가지고 있지 않습니다.",
		"255" : "CMN255 ERROR - Lot은 선택 Carrier에 할당되어 있지 않습니다.",
		"256" : "CMN256 ERROR - Key 문자열 입력이 잘못되었습니다.",
		"257" : "CMN257 ERROR - Data 문자열의 입력이 잘못되었습니다.",
		"258" : "CMN258 ERROR - 이 필드는 필터 문자열이 필요합니다.",
		"259" : "CMN259 ERROR - USL 은 UCL의 값보다 커야합니다. UWL 을 확인해 주세요.",
		"260" : "CMN260 ERROR - LWL 은 LSL의 값보다 커야합니다. LSL 을 확인해 주세요.",
		"261" : "CMN261 ERROR - USL 은 LSL의 값보다 커야합니다. LSL 을 확인해 주세요.",
		"262" : "CMN262 ERROR - UWL 은 LWL의 값보다 커야합니다. LWL 을 확인해 주세요.",
		"263" : "CMN263 ERROR - 이 Collection Set은 선택한 공정에 이미 존재 합니다.",
		"264" : "CMN264 ERROR - 이 Item의 M-F-O(Material-Flow-Operation) 정보가 올바르지 않습니다.",
		"267" : "CMN267 ERROR - Multi Transaction에서 Transaction과 Carrier Change를 동시에 진행할 수 없습니다.",
		"268" : "CMN268 ERROR - Dispatch Rule에 의하여 Lot을 진행 할 수 없습니다.",
		"269" : "CMN269 ERROR - Multi Transaction에서 Transaction과 Alram을 동시에 진행할 수 없습니다.",
		"270" : "CMN270 ERROR - Resource에 Port가 설정되어 있기 떄문에 Multi Transaction을 진행할 수 없습니다.",
		"271" : "CMN271 ERROR - QC Batch의 Material과 Lot의 Material이 일치 하지 않습니다. ",
		"272" : "CMN272 ERROR - 선택된 Resource가 없습니다. 먼저 Resource를 선택하여 주세요.",
		"273" : "CMN273 ERROR - Event에 Collection Set이 설정되어 있기 떄문에 Multi Transaction을 진행할 수 없습니다.",
		"274" : "CMN274 ERROR - 이 Item의 R-G-T(Resource-Group-Type) 정보가 올바르지 않습니다.",
		"275" : "CMN275 ERROR - 이 Tool을 반납하시겠습니까?",
		"276" : "CMN276 ERROR - 이 항목은 이미 존재 합니다.",
		"277" : "CMN277 ERROR - 문자열 개수가 올바르지 않습니다. 입력해주시기바랍니다.",
		"278" : "CMN278 ERROR - 값의 길이가 올바르지 않습니다. 값을 다시 확인해주시기 바랍니다.",
		"279" : "CMN279 ERROR - Service Sequence는 변경할 수 없습니다.",
		"280" : "CMN280 ERROR - Custom rule과 같은 레벨에 설정할 수 없습니다. 레벨을 바꿔주십시오.",
		"281" : "CMN281 ERROR - 이 Class Type은 다른 아이템과 같은 레벨에 설정할 수 없습니다. 레벨을 바꿔주십시오.",
		"282" : "CMN282 ERROR - 이 Lot은 HOLD 중이기 때문에 BATCH를 만들 수 없습니다.",
		"283" : "CMN283 ERROR - 이 Lot은 작업 중이기 때문에 BATCH를 만들 수 없습니다.",
		"284" : "CMN284 ERROR - 이 Lot은 SHIP 중이기 때문에 BATCH를 만들 수 없습니다.",
		"285" : "CMN285 ERROR - 이 Lot은 이미 다른 BATCH에 포함되어 있기 때문에 BATCH를 만들 수 없습니다.",
		"286" : "CMN286 ERROR - 이 인수는 쿼리에서 사용할 수 없습니다.",
		"287" : "CMN287 ERROR - 이 member는 등록되지 않은 멤버입니다. Create 또는 Override를 사용하세요.",
		"288" : "CMN288 ERROR - 이 member는 등록되지 않은 멤버입니다. Override를 사용하세요",
		"289" : "CMN289 ERROR - 새로운 member name으로 member data를 reload하게 됩니다. reload를 하시겠습니까? cancel 하시겠습니까?",
		"290" : "CMN290 ERROR - Override member만 member name이 변경될 수 있습니다! (새로운 member name은 member name에 등록되지 않습니다.",
		"291" : "CMN291 ERROR - 같은 member 이름이 트리 노드안에 이미 존재합니다.",
		"292" : "CMN292 ERROR - Override Uncheck를 할 수 없습니다. 이 member는 등록되지 않은 멤버입니다.",
		"293" : "CMN293 ERROR - 이 Lot은 Sublot을 가지고 있습니다. [Sublot] tab을 사용하세요.",
		"294" : "CMN294 ERROR - Sublot을 캐리어의 빈 Slot에 할당하십시오.",
		"295" : "CMN295 ERROR - 같은 Lot에 속해있는 sublot들을 선택하십시오.",
		"296" : "CMN296 CONFIRM - 이 LOT은 CARRIER에 할당되어 있습니다. CARRIER가 입력되지 않으면 CARRIER와의 관계없이 BONUS가 발생합니다. 그래도 계속 하시겠습니까?",
		"297" : "CMN297 CONFIRM - 선택된 Batch의 구성의 Confirm 상태로부터 Cancel 합니다. Cancel 후에는 해당 Batch에 Lot의 추가,삭제 및 순서변경 작업이 가능하고, 모든 변경 후 Confirm을 해줘야 정상적으로 Batch를 사용할 수 있습니다. Cancel하시겠습까?",
		"298" : "CMN298 CONFIRM - LOT에 SUBLOT이 존재하는 상태에서 UNIT 1의 수량이 증가하므로 New Sublot Grade 값이 필요합니다. \"G\" Grade 로 계속 진행하시겠습니까?",
		"299" : "CMN299 CONFIRM - 연산자 \"IN\" 또는 \"NOT IN\" 은 고정값에서는 허용되지 않습니다.",
		"300" : "CMN300 CONFIRM - GCM 테이블을 사용하는 경우에는 연산자 \"IN\" 또는 \"NOT IN\" 만 가능합니다.",
		"301" : "CMN301 CONFIRM - 입력된 조건과 동일한 조건이 이미 존재합니다.",
		"302" : "CMN302 CONFIRM - 왼쪽 괄호와 오른쪽 괄호의 개수가 맞지 않습니다.",
		"303" : "CMN303 CONFIRM - \"FAC_OA_SERVICES\" GCM 테이블에 서비스를 등록해 주십시오. 서비스 =",
		"304" : "CMN0304 INFO - 이 명령을 수행하면 해당 MFO에 존재하는 모든 Lot에 대해 Pre-Calculation Queue Time이 진행됩니다. 계속 하시겠습니까?",
		"305" : "CMN305 ERROR - 최소한 1개 이상의 아이템을 입력해 주세요.",
		"306" : "CMN306 ERROR - Source Lot와 Target Lot이 동일합니다. 정확한 Lot을 입력하십시오.",
		"307" : "CMN307 ERROR - Source Batch와 Target Batch이 동일합니다. 정확한 Batch을 입력하십시오.",
		"308" : "CMN308 ERROR - UNIT3의 LOSS CODE 수량과 QTY_3의 SCRAP 수량이 일치하지 않습니다.",
		"309" : "CMN309 ERROR - Rework Flow를 지정하지 않으면, Rework 발생시 F-O(Flow-Operation) 관계에서 에러가 발생 할 수있습니다. 계속 하시겠습니까?",
		"310" : "CMN310 ERROR - Key값의 Size는 0과 같거나 크고 100과 같거나 작아야 합니다.",
		"311" : "CMN311 ERROR - Data값의 Size는 0과 같거나 크고 1000과 같거나 작아야 합니다.",
		"312" : "CMN312 ERROR - Tool Status 가 해당 Tool Type 에 존재하지 않습니다. Tool Type 의 Tool Status 를 확인해 보시기 바랍니다.",
		"313" : "CMN313 ERROR - Screen ID를 찾을 수 없습니다. Flexible screen relation이나 Default screen ID를 확인 해 주십시요.",
		"314" : "CMN314 ERROR - Screen의 매크로 탐색에 실패하였습니다.",
		"315" : "CMN315 ERROR - 이 변환 타입은 지원되지 않습니다. 단지 \"DATE\", \"TIME\", \"DATETIME\" 타입만이 지원됩니다.",
		"316" : "CMN316 ERROR - Step을 선택해 주세요."
	}
});
